// PADDLER'S PARADISE — SPRITES & PALETTE (2x set, v0.2.0)
// ---------------------------------------------------------------------------
// Every sprite is a string map drawn in code (house rule: sprite maps +
// nearest-neighbour upscale, no outside art). One character = one TEXEL, and
// as of v0.2.0 there are two texels to a world unit — Evrtek's ruling that
// the game was "maybe too blocky": same framing, double the detail. The
// renderer draws the world at 2x resolution and upscales once, so everything
// still sits on one crisp grid.
// ---------------------------------------------------------------------------

'use strict';

var PAL = {
  // world
  deep:   '#17435f', water: '#1e567a', shallow:'#2b6b8f', ripple:'#3f83a8',
  sand:   '#c9b27c', sandDk: '#a8905e',
  grass:  '#2a5c35', grassDk:'#20492a', forest: '#1b3f24',
  trail:  '#8a6b45', trailDk:'#6f5436',
  rock:   '#8d8d95', rockDk: '#6e6e78',
  // flora
  pine:   '#2c6e3f', pineDk: '#1f5330', pineLt: '#3f8a52',
  birch:  '#e8e4da', birchDk:'#b8b4aa',
  trunk:  '#5d4632', trunkLt:'#7a5c42', lily: '#3f8a4f', lilyFl: '#e8b4c8',
  berry:  '#3b4f9a',
  // things
  canoe:  '#a33e2f', canoeDk:'#7c2c21', canoeLt:'#c05540', paddle: '#c9a86a',
  tent:   '#4a7ab5', tentDk: '#375d8c',
  fire1:  '#e8842a', fire2:  '#f2c14b', ember:  '#8c3a1d',
  signOr: '#e2731f', signYl: '#e8c832', post:   '#4d3a28',
  dock:   '#9a7b52', dockDk: '#7c6140',
  barrel: '#3f6fae', boxWood:'#8a6b45',
  car:    '#d8c391', carLt:  '#efe3bd',
  // creatures
  skin:   '#d9a86c', shirt:  '#b53a3a', shirtDk:'#8c2c2c', hat:    '#3a5c3a',
  moose:  '#5c4230', mooseDk:'#43301f', antler: '#c9b27c',
  loon:   '#1a1a22', loonWh: '#e8e8f0',
  heron:  '#7a8a99', beaver: '#4d3520', turtle: '#3f5c35',
  otter:  '#6b4a2f', deer:   '#a5713f', deerLt: '#c98f57',
  eagleWh:'#f0f0ea', kingf:  '#3a7ab8', bearC:  '#33241a',
  fishSv: '#9fb4c4',
  // ui
  white:  '#f2f2e8', black:  '#10100c', gold:   '#f2c14b',
  bad:    '#d94f4f', good:   '#69c977', uiBg:   'rgba(12,20,16,0.82)',
};

var INK = {
  'w': 'white',  'k': 'black',
  'c': 'canoe',  'C': 'canoeDk', 'z': 'canoeLt', 'p': 'paddle',
  's': 'skin',   'r': 'shirt',   'R': 'shirtDk', 'h': 'hat',
  't': 'tent',   'T': 'tentDk',
  'f': 'fire1',  'F': 'fire2',   'e': 'ember',
  'P': 'pine',   'q': 'pineDk',  'i': 'pineLt',
  'b': 'birch',  'B': 'birchDk', 'u': 'trunk',   'O': 'trunkLt',
  'm': 'moose',  'M': 'mooseDk', 'a': 'antler',
  'l': 'loon',   'L': 'loonWh',
  'H': 'heron',  'v': 'beaver',  'V': 'turtle',
  'I': 'otter',  'A': 'deer',    'E': 'deerLt',
  'J': 'eagleWh','K': 'kingf',   'N': 'bearC',   'S': 'fishSv',
  'o': 'signOr', 'y': 'signYl',  'n': 'post',
  'd': 'dock',   'D': 'dockDk',
  'g': 'lily',   'G': 'lilyFl',  'j': 'berry',
  'x': 'rock',   'X': 'rockDk',
  'W': 'barrel', 'U': 'boxWood',
  '~': 'ripple',
  'Y': 'car',    'Z': 'carLt',   'Q': 'shallow',
};

var MAPS = {

  // --- the tripper, 12x16, facing up --------------------------------------
  // v0.9.0 (#16): the swung leg reaches one texel further and the opposite
  // arm swings back a row, so the two walk frames read as a stride
  walk1: [
    '....hhhh....',
    '...hhhhhh...',
    '...hhhhhh...',
    '....ssss....',
    '....ssss....',
    '.rrrrrrrrrr.',
    'rrrrRRRRrrrr',
    'srrrRRRRrr..',
    '.rrrRRRRrrs.',
    '..rrrrrrrr..',
    '..RRr..rRR..',
    '..kk....kk..',
    '..kk....kk..',
    '..kk........',
    '..kk........',
    '..kk........',
  ],
  walk2: [
    '....hhhh....',
    '...hhhhhh...',
    '...hhhhhh...',
    '....ssss....',
    '....ssss....',
    '.rrrrrrrrrr.',
    'rrrrRRRRrrrr',
    '..rrRRRRrrrs',
    '.srrRRRRrr..',
    '..rrrrrrrr..',
    '..RRr..rRR..',
    '..kk....kk..',
    '..kk....kk..',
    '........kk..',
    '........kk..',
    '........kk..',
  ],
  stand: [
    '....hhhh....',
    '...hhhhhh...',
    '...hhhhhh...',
    '....ssss....',
    '....ssss....',
    '.rrrrrrrrrr.',
    'rrrrRRRRrrrr',
    '.srrRRRRrrs.',
    '..rrRRRRrr..',
    '..rrrrrrrr..',
    '..RRr..rRR..',
    '..kk....kk..',
    '..kk....kk..',
    '..kk....kk..',
    '..kk....kk..',
    '............',
  ],

  // --- the red canoe with paddler, 24x44, bow up ---------------------------
  // v0.9.0 (#11): a 16-footer at real proportions — 12x22 units, open dark
  // hull, bow/stern decks, a bow seat and two thwarts in wood, the paddler on
  // the stern seat, lit gunwale 'z' down the left side, the paddle out to one
  // side per frame (L/R alternate the stroke).
  canoeL: [
    '...........zc...........',
    '..........zcCc..........',
    '.........zcCCCc.........',
    '........zcCCCCCc........',
    '.......zckkkkkkCc.......',
    '.......zckkkkkkCc.......',
    '......zckkkkkkkkCc......',
    '......zcppppppppCc......',
    '......zcppppppppCc......',
    '.....zckkkkkkkkkkCc.....',
    '.....zckkkkkkkkkkCc.....',
    '.....zckkkkkkkkkkCc.....',
    '.....zckkkkkkkkkkCc.....',
    '.....zckkkkkkkkkkCc.....',
    '.....zckkkkkkkkkkCc.....',
    '.....zcppppppppppCc.....',
    '.....zckkkkkkkkkkCc.....',
    '.....zckkkkkkkkkkCc.....',
    '.....zckkkkkkkkkkCc.....',
    '.....zckkkkkkkkkkCc.....',
    '.....zckkkkkkkkkkCc.....',
    '.....zckkkkkkkkkkCc.....',
    '.....zckkkkkkkkkkCc.....',
    '.....zckkkkkkkkkkCc.....',
    '.....zckkkkkkkkkkCc.....',
    '.....zckkkkkkkkkkCc.....',
    '.....zckkkkkkkkkkCc.....',
    '.....zcppppppppppCc.....',
    '.....zckkkkkkkkkkCc.....',
    '.....zckkkkkkkkkkCc.....',
    '.....zckkkkkkkkkkCc.....',
    '.....zckkkhhhhkkkCc.....',
    '.....zckkhhhhhhkkCc.....',
    '..ppppcsshhhhhhkkCc.....',
    'pppp.zcsshhhhhhkkCc.....',
    'ppp..zckrrrrrrrrkCc.....',
    '.....zckrrrRRrrrkCc.....',
    '.....zckkrrrrrrkkCc.....',
    '......zckkkkkkkkCc......',
    '......zckkkkkkkkCc......',
    '.......zckkkkkkCc.......',
    '........zcCCCCCc........',
    '..........zcCc..........',
    '...........zc...........',
  ],
  canoeR: [
    '...........zc...........',
    '..........zcCc..........',
    '.........zcCCCc.........',
    '........zcCCCCCc........',
    '.......zckkkkkkCc.......',
    '.......zckkkkkkCc.......',
    '......zckkkkkkkkCc......',
    '......zcppppppppCc......',
    '......zcppppppppCc......',
    '.....zckkkkkkkkkkCc.....',
    '.....zckkkkkkkkkkCc.....',
    '.....zckkkkkkkkkkCc.....',
    '.....zckkkkkkkkkkCc.....',
    '.....zckkkkkkkkkkCc.....',
    '.....zckkkkkkkkkkCc.....',
    '.....zcppppppppppCc.....',
    '.....zckkkkkkkkkkCc.....',
    '.....zckkkkkkkkkkCc.....',
    '.....zckkkkkkkkkkCc.....',
    '.....zckkkkkkkkkkCc.....',
    '.....zckkkkkkkkkkCc.....',
    '.....zckkkkkkkkkkCc.....',
    '.....zckkkkkkkkkkCc.....',
    '.....zckkkkkkkkkkCc.....',
    '.....zckkkkkkkkkkCc.....',
    '.....zckkkkkkkkkkCc.....',
    '.....zckkkkkkkkkkCc.....',
    '.....zcppppppppppCc.....',
    '.....zckkkkkkkkkkCc.....',
    '.....zckkkkkkkkkkCc.....',
    '.....zckkkkkkkkkkCc.....',
    '.....zckkkhhhhkkkCc.....',
    '.....zckkhhhhhhkkCc.....',
    '.....zckkhhhhhhssCpppp..',
    '.....zckkhhhhhhssCc.pppp',
    '.....zckrrrrrrrrkCc..ppp',
    '.....zckrrrRRrrrkCc.....',
    '.....zckkrrrrrrkkCc.....',
    '......zckkkkkkkkCc......',
    '......zckkkkkkkkCc......',
    '.......zckkkkkkCc.......',
    '........zcCCCCCc........',
    '..........zcCc..........',
    '...........zc...........',
  ],

  // --- portaging: hull overhead, legs under, 24x44 -------------------------
  // v0.9.0 (#11): the hull is carried upside down and bow-high, so from above
  // it is the keel side ('C' keel line) foreshortened to 35 rows; shoulders
  // and the striding legs show past the stern.
  carry1: [
    '...........zc...........',
    '..........zCCc..........',
    '.........zcCCcc.........',
    '........zccCCccc........',
    '.......zcccCCcccc.......',
    '.......zcccCCcccc.......',
    '......zccccCCccccc......',
    '......zccccCCccccc......',
    '.....zcccccCCcccccc.....',
    '.....zcccccCCcccccc.....',
    '.....zcccccCCcccccc.....',
    '.....zcccccCCcccccc.....',
    '.....zcccccCCcccccc.....',
    '.....zcccccCCcccccc.....',
    '.....zcccccCCcccccc.....',
    '.....zcccccCCcccccc.....',
    '.....zcccccCCcccccc.....',
    '.....zcccccCCcccccc.....',
    '.....zcccccCCcccccc.....',
    '.....zcccccCCcccccc.....',
    '.....zcccccCCcccccc.....',
    '.....zcccccCCcccccc.....',
    '.....zcccccCCcccccc.....',
    '.....zcccccCCcccccc.....',
    '.....zcccccCCcccccc.....',
    '.....zcccccCCcccccc.....',
    '.....zcccccCCcccccc.....',
    '......zccccCCccccc......',
    '......zccccCCccccc......',
    '.......zcccCCcccc.......',
    '.......zcccCCcccc.......',
    '........zccCCccc........',
    '.........zcCCcc.........',
    '..........zCCc..........',
    '...........zc...........',
    '.........rrrrrr.........',
    '........RRrrrrRR........',
    '.........rrrrrr.........',
    '.........kk..kk.........',
    '.........kk..kk.........',
    '.........kk..kk.........',
    '.........kk.............',
    '.........kk.............',
    '........................',
  ],
  carry2: [
    '...........zc...........',
    '..........zCCc..........',
    '.........zcCCcc.........',
    '........zccCCccc........',
    '.......zcccCCcccc.......',
    '.......zcccCCcccc.......',
    '......zccccCCccccc......',
    '......zccccCCccccc......',
    '.....zcccccCCcccccc.....',
    '.....zcccccCCcccccc.....',
    '.....zcccccCCcccccc.....',
    '.....zcccccCCcccccc.....',
    '.....zcccccCCcccccc.....',
    '.....zcccccCCcccccc.....',
    '.....zcccccCCcccccc.....',
    '.....zcccccCCcccccc.....',
    '.....zcccccCCcccccc.....',
    '.....zcccccCCcccccc.....',
    '.....zcccccCCcccccc.....',
    '.....zcccccCCcccccc.....',
    '.....zcccccCCcccccc.....',
    '.....zcccccCCcccccc.....',
    '.....zcccccCCcccccc.....',
    '.....zcccccCCcccccc.....',
    '.....zcccccCCcccccc.....',
    '.....zcccccCCcccccc.....',
    '.....zcccccCCcccccc.....',
    '......zccccCCccccc......',
    '......zccccCCccccc......',
    '.......zcccCCcccc.......',
    '.......zcccCCcccc.......',
    '........zccCCccc........',
    '.........zcCCcc.........',
    '..........zCCc..........',
    '...........zc...........',
    '.........rrrrrr.........',
    '........RRrrrrRR........',
    '.........rrrrrr.........',
    '.........kk..kk.........',
    '.........kk..kk.........',
    '.........kk..kk.........',
    '.............kk.........',
    '.............kk.........',
    '........................',
  ],

  // the empty hull hauled out, plan view lying horizontal, 44x14 (#11):
  // open interior, two thwarts, bow and stern seats, lit gunwale on top
  canoeBeached: [
    '..............zzzzzzzzzzzzzzzz..............',
    '.........zzzzzCCCCCCCCCCCCCCCCccccc.........',
    '......zccCCCCCppkkkkkkkkkkkkppCCCCCccc......',
    '....zcCCCkkkkkppkkkkkkkkkkkkppkkkkkCCCcc....',
    '..zzCCkkkkkkkkppkkkkkkkkkkkkppkkkkkkkkCCcc..',
    '.zCCkkkppkkkkkppkkkkkkkkkkkkppkkkkkppkkkCCc.',
    'zCkkkkkppkkkkkppkkkkkkkkkkkkppkkkkkppkkkkkCc',
    'cCkkkkkppkkkkkppkkkkkkkkkkkkppkkkkkppkkkkkCc',
    '.cCCkkkppkkkkkppkkkkkkkkkkkkppkkkkkppkkkCCc.',
    '..ccCCkkkkkkkkppkkkkkkkkkkkkppkkkkkkkkCCcc..',
    '....ccCCCkkkkkppkkkkkkkkkkkkppkkkkkCCCcc....',
    '......cccCCCCCppkkkkkkkkkkkkppCCCCCccc......',
    '.........cccccCCCCCCCCCCCCCCCCccccc.........',
    '..............cccccccccccccccc..............',
  ],

  // --- flora, 2x ------------------------------------------------------------
  // v0.9.0 (#14): these two are now the UNDERSTORY (pineSm/birchSm); the
  // full-size pine and birch are appended at the end of the file.
  pineSm: [
    '........i.........',
    '.......iPi........',
    '......iPPPq.......',
    '.....iPPPPPq......',
    '......iPPPq.......',
    '.....iPPPPPq......',
    '....iPPPPPPPq.....',
    '...iPPPPPPPPPq....',
    '.....iPPPPPq......',
    '....iPPPPPPPq.....',
    '...iPPPPPPPPPq....',
    '..iPPPPPPPPPPPq...',
    '....iPPPPPPPq.....',
    '...iPPPPPPPPPq....',
    '..iPPPPPPPPPPPq...',
    '.iPPPPPPPPPPPPPq..',
    'iPPPPPPPPPPPPPPPq.',
    '.qqqPPPPPPPPPqqq..',
    '........Ou........',
    '........Ou........',
    '........Ou........',
    '.......OOuu.......',
    '..................',
    '..................',
  ],
  birchSm: [
    '.....iPPPi....',
    '...iPPPPPPPi..',
    '..iPPqPPqPPPi.',
    '.iPPPPPPPPPPi.',
    '.iPqPPPPPqPPi.',
    '..iPPPPPPPPi..',
    '...iPPPPPPi...',
    '.....PPPP.....',
    '......bb......',
    '......bB......',
    '......bb......',
    '......Bb......',
    '......bb......',
    '......bB......',
    '......bb......',
    '......bb......',
    '.....bbBb.....',
    '..............',
    '..............',
    '..............',
    '..............',
    '..............',
    '..............',
    '..............',
  ],
  rock: [
    '.....xxxx.....',
    '...xxxxxxxx...',
    '..xxXxxxxXxx..',
    '.xxxxxXXxxxxx.',
    'xxXXxxxxxxXXxx',
    '.XXXXXXXXXXXX.',
    '..............',
    '..............',
  ],
  lily: [
    '..gggg..ggG.',
    '.gggggg.ggg.',
    'ggggkggggg..',
    '.gggggg.....',
    '..gggg......',
    '............',
  ],

  // --- camp, 2x -------------------------------------------------------------
  tent: [
    '...........tt...........',
    '..........tttt..........',
    '.........tttttt.........',
    '........tttttttt........',
    '.......tttTTTTttt.......',
    '......tttTTTTTTttt......',
    '.....tttTTTTTTTTttt.....',
    '....tttTTTkkkkTTTttt....',
    '...tttTTTTkkkkTTTTttt...',
    '..tttTTTTTkkkkTTTTTttt..',
    '.tttTTTTTTkkkkTTTTTTttt.',
    'tttTTTTTTTkkkkTTTTTTTttt',
    'uu..................uu..',
    '........................',
    '........................',
    '........................',
    '........................',
    '........................',
    '........................',
    '........................',
  ],
  fire1: [
    '.....F......',
    '....fFf.....',
    '....fFFf....',
    '...ffFFf....',
    '...fFFFFf...',
    '..ffFFFFff..',
    '..fffFFfff..',
    '.effffffffe.',
    '.xeeeeeeeex.',
    'xx.x.xx.x.xx',
    '............',
    '............',
  ],
  fire2: [
    '......f.....',
    '.....Ff.....',
    '....fFFf....',
    '....FFff....',
    '...fFFFFf...',
    '..fFFffFFf..',
    '..ffFFFFff..',
    '.effffffffe.',
    '.xeeeeeeeex.',
    'xx.x.xx.x.xx',
    '............',
    '............',
  ],
  firering: [
    '..xx.xx.xx..',
    '.x..x..x..x.',
    '.x.eeeeee.x.',
    'xx.eekkee.xx',
    '.x.eeeeee.x.',
    '.x..x..x..x.',
    '..xx.xx.xx..',
    '............',
  ],
  bench: [
    'OOOOOOOOOOOOOOOO',
    'OuuuuuuuuuuuuuOO',
    '.uu..........uu.',
    '.uu..........uu.',
    '................',
    '................',
  ],
  barrel: [
    '..WWWW..',
    '.WWWWWW.',
    '.WkWWkW.',
    '.WWWWWW.',
    '.WWWWWW.',
    '.WkWWkW.',
    '.WWWWWW.',
    '..WWWW..',
    '........',
    '........',
    '........',
    '........',
  ],
  barrelHung: [
    '.....uu.....',
    '.....kk.....',
    '.....kk.....',
    '....WWWW....',
    '...WWWWWW...',
    '...WkWWkW...',
    '...WWWWWW...',
    '...WkWWkW...',
    '...WWWWWW...',
    '....WWWW....',
    '............',
    '............',
    '............',
    '............',
    '............',
    '............',
    '............',
    '............',
    '............',
    '............',
  ],
  thunderbox: [
    '..UUUUUUUU..',
    '.UUUUUUUUUU.',
    '.UUnnnnnnUU.',
    '.UUnkkkknUU.',
    '.UUnnnnnnUU.',
    '.UUUUUUUUUU.',
    '.UU......UU.',
    '............',
    '............',
    '............',
    '............',
    '............',
  ],
  deadfall: [
    '..OuuO......',
    '.OuuuuOuu...',
    'uuOuuuuuuOu.',
    '..uuOOuuuu..',
    '............',
    '............',
    '............',
    '............',
  ],

  // --- signs & furniture, 2x ------------------------------------------------
  campSign: [
    'oooooooo',
    'oo.kk.oo',
    'o.kkkk.o',
    'oo.kk.oo',
    'oooooooo',
    '...nn...',
    '...nn...',
    '...nn...',
    '...nn...',
    '...nn...',
    '...nn...',
    '........',
    '........',
    '........',
    '........',
    '........',
  ],
  portSign: [
    'yyyyyyyy',
    'yy.kk.yy',
    'y..kk..y',
    'y.kkkk.y',
    'yyyyyyyy',
    '...nn...',
    '...nn...',
    '...nn...',
    '...nn...',
    '...nn...',
    '...nn...',
    '........',
    '........',
    '........',
    '........',
    '........',
  ],
  board: [
    'nnnnnnnnnnnnnnnnnnnn',
    'nwwwwwwwwwwwwwwwwwwn',
    'nwkkwkwwkkkwwkwkkwwn',
    'nwwwwwwwwwwwwwwwwwwn',
    'nwkwkkwwkwkkkwwkkwwn',
    'nwwwwwwwwwwwwwwwwwwn',
    'nwkkkwkwwkkwwkwkwwwn',
    'nwwwwwwwwwwwwwwwwwwn',
    'nnnnnnnnnnnnnnnnnnnn',
    '.......nn...........',
    '.......nn...........',
    '.......nn...........',
    '.......nn...........',
    '....................',
    '....................',
    '....................',
    '....................',
    '....................',
  ],

  // --- wildlife, 2x ---------------------------------------------------------
  // v0.9.0 (#18): one rack, over the head at the left; shoulder hump behind
  // the neck and a rounded rump at the right
  moose: [
    'aa...aa.....................',
    '.aa.aa......................',
    '..aaa.......................',
    '...mm.......................',
    '...mmm.mmmmmm...............',
    '....mmmmmmmmmmmmmmm.........',
    '...mmmmmmmmmmmmmmmmm........',
    '..MmmmmmmmmmmmmmmmmM........',
    '.kMMmmmmmmmmmmmmmmmM........',
    '..MM.mmmmmmmmmmmmmM.........',
    '.....Mm..Mm..mM..mM.........',
    '.....Mm..Mm..mM..mM.........',
    '.....MM..MM..MM..MM.........',
    '............................',
    '............................',
    '............................',
    '............................',
    '............................',
    '............................',
    '............................',
    '............................',
    '............................',
  ],
  loon: [
    '..kk............',
    '.kkkk...........',
    'kkkkk...........',
    '.kkLLkkkkkkk....',
    '.kklLkLkLkLkk...',
    '..kkllkLkLklk...',
    '...kllllllllk...',
    '....llllllll....',
    '................',
    '................',
  ],
  heron: [
    '..kkk.......',
    '..HHHk......',
    '...HH.......',
    '...HH.......',
    '...HHH......',
    '....HHH.....',
    '...HHHHHH...',
    '..HHHHHHHH..',
    '..HHHHHHHH..',
    '...HHHHHH...',
    '....HHHH....',
    '.....HH.....',
    '.....kk.....',
    '.....kk.....',
    '....kk.k....',
    '............',
    '............',
    '............',
    '............',
    '............',
  ],
  beaver: [
    '...vvvvvv.....',
    '..vvvvvvvv....',
    '.kvvvvvvvvv...',
    '.vvvvvvvvvv...',
    '..vvvvvvvv....',
    '....kkkkkkkk..',
    '....kkkkkkkk..',
    '..............',
    '..............',
    '..............',
  ],
  turtle: [
    '...VVVVVV...',
    '..VVkVVkVV..',
    '.VVVVVVVVVV.',
    'kVVVVVVVVVVk',
    '.V.V....V.V.',
    '............',
    '............',
    '............',
  ],
  otter: [
    '.II.............',
    'IkII............',
    '.IIII...........',
    '..IIIIIIIII.....',
    '...IIIIIIIIIII..',
    '.....IIII...III.',
    '................',
    '................',
  ],
  deer: [
    '.a..a...............',
    '.aa.aa..............',
    '..AAA...............',
    '..AAk...............',
    '..AA................',
    '..AAEEEEEEEEE.......',
    '..AEEEEEEEEEEE......',
    '...EEEEEEEEEEE......',
    '...EE.EE..EE.EE.....',
    '...EE.EE..EE.EE.....',
    '...AA.AA..AA.AA.....',
    '....................',
    '....................',
    '....................',
    '....................',
    '....................',
    '....................',
    '....................',
    '....................',
    '....................',
  ],
  eagle: [
    'kk..................',
    '.kkk................',
    '..kkkkk....JJ.......',
    '...kkkkkkkJJk.......',
    '....kkkkkkkkkk......',
    '...kkkkkkkkk........',
    '..kkkkk.............',
    '.kkk................',
    'kk..................',
    '....................',
  ],
  kingfisher: [
    '..KKk.....',
    '.KKKKk....',
    'kKLKKK....',
    '.KKKKKKK..',
    '..KKKKK...',
    '...KK.....',
    '..........',
    '..........',
    '..........',
    '..........',
  ],
  bear: [
    '..NN..............NN..',
    '.NNNN............NNNN.',
    '.NNNNNNNNNNNNNNNNNNNN.',
    'NNNNNNNNNNNNNNNNNNNNNN',
    'NkNNNNNNNNNNNNNNNNNNNN',
    'NNNNNNNNNNNNNNNNNNNNN.',
    '.NNN.NNN......NNN.NNN.',
    '.NNN.NNN......NNN.NNN.',
    '......................',
    '......................',
    '......................',
    '......................',
    '......................',
    '......................',
    '......................',
    '......................',
  ],
  splash: [
    '....S.......',
    '.S..S...S...',
    '..S.SS.S....',
    '...SSSS.....',
    '..SSSSSS....',
    '.SSSSSSSS...',
    '............',
    '............',
  ],
  fish: [
    '....SSSS....',
    '..SSSSSSSk..',
    '.SSSSSSSSSS.',
    '..SSSSSSS...',
    '....SSSS....',
    '......S.....',
    '............',
    '............',
  ],
};

// --- builder ----------------------------------------------------------------

var SPRITES = {};

function buildSprite(name, rows, ink) {
  var h = rows.length, w = 0, y, x;
  for (y = 0; y < h; y++) w = Math.max(w, rows[y].length);
  var c = document.createElement('canvas');
  c.width = w; c.height = h;
  var g = c.getContext('2d');
  for (y = 0; y < h; y++) {
    for (x = 0; x < rows[y].length; x++) {
      var ch = rows[y][x];
      if (ch === '.' || ch === ' ') continue;
      var key = ink[ch];
      if (!key) continue;
      g.fillStyle = PAL[key];
      g.fillRect(x, y, 1, 1);
    }
  }
  SPRITES[name] = c;
  return c;
}

function buildAllSprites() {
  var name;
  for (name in MAPS) buildSprite(name, MAPS[name], INK);
  // the objective chevron, in gold — and (v0.9.0, #19) the same chevron in
  // canoe red, the pointer back to a beached boat
  var chevron = [
    'gg........gg',
    'ggg......ggg',
    '.ggg....ggg.',
    '..ggg..ggg..',
    '...gggggg...',
    '....gggg....',
    '.....gg.....',
    '............',
  ];
  buildSprite('marker', chevron, { g: 'gold' });
  buildSprite('markerRed', chevron, { g: 'canoe' });
}

// ---------------------------------------------------------------------------
// THE CAMP SET — high-fidelity sprites for the campsite scene (v0.3.0).
// The camp is a SCENE SWITCH, not a zoom (Evrtek's ruling): its own stage at
// four texels per world unit, double the overworld's density. These maps are
// drawn at that density — twice the linear detail of the overworld set — and
// only ever appear inside the camp scene.
//
// v0.9.2 uplift (Evrtek's play note: the camp props "require too much
// interpretation"): the furniture and firewood were redrawn for legibility at
// PHONE scale, where one texel is one framebuffer pixel on a two-inch-wide
// stage — high-contrast silhouettes, one readable highlight per prop, no
// one-texel detail. Every map keeps its dimensions except the snag, the
// fallen log and the three woodpiles, which grew with their content kept in
// the top rows so each stands where it stood.
// ---------------------------------------------------------------------------

var HD_MAPS = {

  hdStand: [
    '.........hhhhhh.........',
    '........hhhhhhhh........',
    '.......hhhhhhhhhh.......',
    '.......hhhhhhhhhh.......',
    '........ssssssss........',
    '........sskssks.........',
    '........ssssssss........',
    '.........ssssss.........',
    '....rrrrrRRrrRRrrrr.....',
    '...rrrrrrRRrrRRrrrrr....',
    '..rrrRRrrrrrrrrrrRRrr...',
    '..srrRRrrrrRRrrrrRRrrs..',
    '..ssrrrrrrRRRRrrrrrrss..',
    '..ssrrRRrrRRRRrrRRrrss..',
    '...srrRRrrrrrrrrRRrrs...',
    '....rrrrrrRRRRrrrrrr....',
    '.....rrrrrrrrrrrrrr.....',
    '......nnnnnnnnnnnn......',
    '......nnnnnnnnnnnn......',
    '......nnnn....nnnn......',
    '......nnnn....nnnn......',
    '......nnnn....nnnn......',
    '......nnnn....nnnn......',
    '......nnnn....nnnn......',
    '......kkkk....kkkk......',
    '.....kkkkk....kkkkk.....',
    '........................',
    '........................',
    '........................',
    '........................',
    '........................',
    '........................',
  ],
  // v0.9.0 (#16): the swung leg reaches two texels (half a unit) further and
  // the opposite arm swings back two rows, so the pair reads as a stride
  hdWalk1: [
    '.........hhhhhh.........',
    '........hhhhhhhh........',
    '.......hhhhhhhhhh.......',
    '.......hhhhhhhhhh.......',
    '........ssssssss........',
    '........sskssks.........',
    '........ssssssss........',
    '.........ssssss.........',
    '....rrrrrRRrrRRrrrr.....',
    '...rrrrrrRRrrRRrrrrr....',
    '..rrrRRrrrrrrrrrrRRrr...',
    '..rrrRRrrrrRRrrrrRRrrs..',
    '..rrrrrrrrRRRRrrrrrrss..',
    '..ssrrRRrrRRRRrrRRrrss..',
    '..ssrrRRrrrrrrrrRRrrs...',
    '..ssrrrrrrRRRRrrrrrr....',
    '...ssrrrrrrrrrrrrrr.....',
    '......nnnnnnnnnnnn......',
    '......nnnnnnnnnnnn......',
    '......nnnn....nnnn......',
    '......nnnn....nnnn......',
    '......nnnn....nnnn......',
    '......nnnn......nnnn....',
    '......nnnn......nnnn....',
    '......kkkk......nnnn....',
    '.....kkkkk......nnnn....',
    '................kkkk....',
    '...............kkkkk....',
    '........................',
    '........................',
    '........................',
    '........................',
  ],
  hdWalk2: [
    '.........hhhhhh.........',
    '........hhhhhhhh........',
    '.......hhhhhhhhhh.......',
    '.......hhhhhhhhhh.......',
    '........ssssssss........',
    '........sskssks.........',
    '........ssssssss........',
    '.........ssssss.........',
    '....rrrrrRRrrRRrrrr.....',
    '...rrrrrrRRrrRRrrrrr....',
    '..rrrRRrrrrrrrrrrRRrr...',
    '..srrRRrrrrRRrrrrRRrrr..',
    '..ssrrrrrrRRRRrrrrrrrr..',
    '..ssrrRRrrRRRRrrRRrrss..',
    '...srrRRrrrrrrrrRRrrss..',
    '....rrrrrrRRRRrrrrrrss..',
    '.....rrrrrrrrrrrrrrss...',
    '......nnnnnnnnnnnn......',
    '......nnnnnnnnnnnn......',
    '......nnnn....nnnn......',
    '......nnnn....nnnn......',
    '......nnnn....nnnn......',
    '....nnnn......nnnn......',
    '....nnnn......nnnn......',
    '....nnnn......kkkk......',
    '....nnnn.....kkkkk......',
    '....kkkk................',
    '...kkkkk................',
    '........................',
    '........................',
    '........................',
    '........................',
  ],

  hdTent: [
    '......................tttt......................',
    '....................tttttttt....................',
    '..................tttttttttttt..................',
    '................tttttttttttttttt................',
    '..............tttttttttttttttttttt..............',
    '............ttttttTTTTTTTTTTtttttttt............',
    '..........ttttttTTTTTTTTTTTTTTtttttttt..........',
    '........ttttttTTTTTTTTTTTTTTTTTTtttttttt........',
    '......ttttttTTTTTTTkkkkkkkkTTTTTTTtttttttt......',
    '.....tttttTTTTTTTkkkkkkkkkkkkTTTTTTTttttttt.....',
    '....tttttTTTTTTTkkkkkkkkkkkkkkTTTTTTTtttttt.....',
    '...tttttTTTTTTTkkkkkkkkkkkkkkkkTTTTTTTttttt.....',
    '..tttttTTTTTTTkkkkkkkkkkkkkkkkkkTTTTTTTtttt.....',
    '.tttttTTTTTTTkkkkkkkkkkkkkkkkkkkkTTTTTTTttt.....',
    'ttttttTTTTTTkkkkkkkkkkkkkkkkkkkkkkTTTTTTtttt....',
    'uuu...................................uuu.......',
    'uuu...................................uuu.......',
    '.................................................',
    '.................................................',
    '.................................................',
  ],

  hdFire1: [
    '..........FF.............',
    '.........FFf.............',
    '........fFFf.............',
    '........fFFFf............',
    '.......fFFFFFf...........',
    '......ffFFFFff...........',
    '......fFFffFFFf..........',
    '.....ffFFFFFFff..........',
    '....fffFFFFFFfff.........',
    '....ffffFFFFffff.........',
    '...efffffffffffe.........',
    '...eefffffffffee.........',
    '..xeeeeeeeeeeeeex........',
    '.xx.xx.xxxx.xx.xx........',
    '.........................',
    '.........................',
  ],
  hdFire2: [
    '............ff...........',
    '...........fFf...........',
    '..........fFFf...........',
    '.........fFFFFf..........',
    '........fFFffFf..........',
    '.......ffFFFFFFf.........',
    '......fFFFffFFFf.........',
    '.....ffFFFFFFFff.........',
    '....fffFFFFFFfff.........',
    '....ffffFFFFffff.........',
    '...efffffffffffe.........',
    '...eefffffffffee.........',
    '..xeeeeeeeeeeeeex........',
    '.xx.xx.xxxx.xx.xx........',
    '.........................',
    '.........................',
  ],
  hdRing: [
  '.....xxx...xxx.....',
  '...xxXXXxxxXXXxx...',
  '..xXX.eeeeeee.XXx..',
  '.xxX.eekkkkkee.Xxx.',
  '.xXX.ekkkkkkke.XXx.',
  '.xxX.eekkkkkee.Xxx.',
  '..xXX.eeeeeee.XXx..',
  '...xxXXXxxxXXXxx...',
  '.....xxx...xxx.....',
  '...................',
  ],

  hdBench: [
  '.pppppppppppppppppppppppppppppp.',
  'pppppppppppppppppppppppppppppppp',
  'uuOuuuuuOuuuuuuuuOuuuuuuuOuuuuuu',
  'uuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuu',
  '...nnnn..................nnnn...',
  '...nnnn..................nnnn...',
  '..kkkkkk................kkkkkk..',
  '................................',
  ],

  hdBarrel: [
  '....kkkkkkkk....',
  '..kkSSSSSSSSkk..',
  '.kkkkkkkkkkkkkk.',
  '.W~~WWWWWWWWWTT.',
  '.W~~WWWWWWWWWTT.',
  '.kkkkkkkkkkkkkk.',
  '.W~~WWWWWWWWWTT.',
  '.W~~WWWWWWWWWTT.',
  '.W~~WWWWWWWWWTT.',
  '.W~~WWWWWWWWWTT.',
  '.kkkkkkkkkkkkkk.',
  '.W~~WWWWWWWWWTT.',
  '.W~~WWWWWWWWWTT.',
  '.WW~WWWWWWWWWTT.',
  '..kWWWWWWWWWWk..',
  '...kkkkkkkkkk...',
  '................',
  '................',
  '................',
  '................',
  '................',
  '................',
  '................',
  '................',
  ],
  hdBarrelHung: [
  '...........OO...........',
  '...........OO...........',
  '..........kOOk..........',
  '........kkkkkkkk........',
  '......kkSSSSSSSSkk......',
  '.....kkkkkkkkkkkkkk.....',
  '.....W~~WWWWWWWWWTT.....',
  '.....W~~WWWWWWWWWTT.....',
  '.....kkkkkkkkkkkkkk.....',
  '.....W~~WWWWWWWWWTT.....',
  '.....W~~WWWWWWWWWTT.....',
  '.....W~~WWWWWWWWWTT.....',
  '.....W~~WWWWWWWWWTT.....',
  '.....kkkkkkkkkkkkkk.....',
  '.....W~~WWWWWWWWWTT.....',
  '.....W~~WWWWWWWWWTT.....',
  '.....WW~WWWWWWWWWTT.....',
  '......kWWWWWWWWWWk......',
  '.......kkkkkkkkkk.......',
  '........................',
  '........................',
  '........................',
  '........................',
  '........................',
  '........................',
  '........................',
  '........................',
  '........................',
  '........................',
  '........................',
  '........................',
  '........................',
  '........................',
  '........................',
  '........................',
  '........................',
  '........................',
  '........................',
  '........................',
  '........................',
  ],

  hdBox: [
  '...UUUUUUUUUUUUUUUUUU...',
  '...UppppppppppppppppU...',
  '...UppppppppppppppppU...',
  '...UppppppppppppppppU...',
  '...UppppppppppppppppU...',
  '..kkkkkkkkkkkkkkkkkkkk..',
  '..UddddddddddddddddddU..',
  '..UdddddkkkkkkkkdddddU..',
  '..UddddkkkkkkkkkkddddU..',
  '..UdddddkkkkkkkkdddddU..',
  '..UUUUUUUUUUUUUUUUUUUU..',
  '..DUUUUUUUUUUUUUUUUUUD..',
  '..DUUUUUUUUUUUUUUUUUUD..',
  '..DDDDDDDDDDDDDDDDDDDD..',
  '..DUUUUUUUUUUUUUUUUUUD..',
  '..kkkkkkkkkkkkkkkkkkkk..',
  ],

  // a fallen limb with its broken pale end, and three bucked rounds showing
  // their end grain — wood that reads as WOOD (Evrtek's note). Also the
  // shore's driftwood, drawn at native size into the camp floor.
  hdDeadfall: [
  '.........O.......O..........',
  '.uOOOOOOOOOOOOOOOOOOOOOOOBB.',
  'uuuuuuuBuuuuuuuBuuuuuuuuupp.',
  'uuuuuuuuuuuuuuuuuuuuuuuuuBB.',
  '.nnnnnnnnnnnnnnnnnnnnnnnnn..',
  '............................',
  '...uOOOOu...uOOOOu...uOOOOu.',
  '..uOppppOu.uOppppOu.uOppppOu',
  '..uOppppOu.uOppppOu.uOppppOu',
  '..uOpOOpOu.uOpOOpOu.uOpOOpOu',
  '..uOppppOu.uOppppOu.uOppppOu',
  '...uOOOOu...uOOOOu...uOOOOu.',
  '...nnnnnn...nnnnnn...nnnnnn.',
  '............................',
  '............................',
  '............................',
  ],
  hdTentBundle: [
  '....................',
  '..tttttttttttttttt..',
  '.ptttkkttttttttkkttp',
  '.pttTkkTTTTTTTTkkTTp',
  '..TTTTkkTTTTTTTTkkT.',
  '...TTTTTTTTTTTTTTT..',
  '....................',
  '....................',
  ],

  hdCanoe: [
    '....zzcccccccccccccccczz........',
    '..zzccCCCCCCCCCCCCCCCCcczz......',
    '.zccCCCCkkkkkkkkkkkkCCCCccz.....',
    'zccCCCCCkkkkkkkkkkkkCCCCCccz....',
    'zccCCCCCCCCCCCCCCCCCCCCCCccz....',
    '.zccCCCCCCCCCCCCCCCCCCCCccz.....',
    '..zzccCCCCCCCCCCCCCCCCcczz......',
    '....zzcccccccccccccccczz........',
    '................................',
    '................................',
    '................................',
    '................................',
    '................................',
    '................................',
    '................................',
    '................................',
  ],

  hdPine: [
    '................ii................',
    '...............iPPi...............',
    '..............iPPPPq..............',
    '.............iPPPPPPq.............',
    '............iPPPPPPPPq............',
    '..............iPPPPq..............',
    '.............iPPPPPPq.............',
    '...........iPPPPPPPPPPq...........',
    '..........iPPPPPPPPPPPPq..........',
    '............iPPPPPPPPq............',
    '..........iPPPPPPPPPPPPq..........',
    '........iPPPPPPPPPPPPPPPPq........',
    '..........iPPPPPPPPPPPPq..........',
    '........iPPPPPPPPPPPPPPPPq........',
    '......iPPPPPPPPPPPPPPPPPPPPq......',
    '....iPPPPPPPPPPPPPPPPPPPPPPPPq....',
    '..iPPPPPPPPPPPPPPPPPPPPPPPPPPPPq..',
    '...qqqqPPPPPPPPPPPPPPPPPPPPqqqq...',
    '...............OOuu...............',
    '...............OOuu...............',
    '...............OOuu...............',
    '...............OOuu...............',
    '..............OOOuuu..............',
    '..................................',
    '..................................',
    '..................................',
    '..................................',
    '..................................',
    '..................................',
    '..................................',
    '..................................',
    '..................................',
    '..................................',
    '..................................',
    '..................................',
    '..................................',
    '..................................',
    '..................................',
    '..................................',
    '..................................',
    '..................................',
    '..................................',
    '..................................',
    '..................................',
    '..................................',
    '..................................',
    '..................................',
    '..................................',
  ],
  hdBirch: [
    '..........iPPPPPi.........',
    '.......iPPPPPPPPPPi.......',
    '.....iPPPPqPPPPqPPPPi.....',
    '....iPPPPPPPPPPPPPPPPi....',
    '...iPPqPPPPPPPPPPPqPPPi...',
    '...iPPPPPPPPqPPPPPPPPPi...',
    '....iPPPPPPPPPPPPPPPPi....',
    '.....iPPPPPPPPPPPPPPi.....',
    '.......iPPPPPPPPPPi.......',
    '..........PPPPPP..........',
    '...........bbbb...........',
    '...........bbbB...........',
    '...........bbbb...........',
    '...........Bbbb...........',
    '...........bbbb...........',
    '...........bbbB...........',
    '...........bbbb...........',
    '...........bbbb...........',
    '...........Bbbb...........',
    '...........bbbb...........',
    '..........bbbBbb..........',
    '..........................',
    '..........................',
    '..........................',
    '..........................',
    '..........................',
    '..........................',
    '..........................',
    '..........................',
    '..........................',
    '..........................',
    '..........................',
    '..........................',
    '..........................',
    '..........................',
    '..........................',
    '..........................',
    '..........................',
    '..........................',
    '..........................',
    '..........................',
    '..........................',
  ],
  hdRock: [
    '..........xxxxxxxx...........',
    '......xxxxxxxxxxxxxx.........',
    '....xxxxXXxxxxxxXXxxxx.......',
    '..xxxxxxxxxxXXxxxxxxxxxx.....',
    '.xxxXXxxxxxxxxxxxxxxXXxxx....',
    '.XXXXXXXXXXXXXXXXXXXXXXXX....',
    '.............................',
    '.............................',
  ],
  hdSign: [
  'kkkkkkkkkkkkkkkk',
  'kooooooooooooook',
  'kooooookkooooook',
  'koooookkkkoooook',
  'kooookkkkkkooook',
  'koookkkkkkkkoook',
  'kookkkkookkkkook',
  'kooooooooooooook',
  'kkkkkkkkkkkkkkkk',
  '......nnnn......',
  '......nnnn......',
  '......nnnn......',
  '......nnnn......',
  '......nnnn......',
  '......nnnn......',
  '......nnnn......',
  '................',
  '................',
  '................',
  '................',
  '................',
  '................',
  '................',
  '................',
  '................',
  '................',
  '................',
  '................',
  '................',
  '................',
  '................',
  '................',
  ],
  hdTuft: [
    '.g..g.g.',
    'g.gg.g..',
    '.g.g..g.',
    '........',
  ],
};

function buildHDSprites() {
  var name;
  for (name in HD_MAPS) buildSprite(name, HD_MAPS[name], INK);
}

// --- deterministic PRNG (mulberry32) ---------------------------------------
function rngFrom(seed) {
  var a = seed >>> 0;
  return function () {
    a |= 0; a = (a + 0x6D2B79F5) | 0;
    var t = Math.imul(a ^ (a >>> 15), 1 | a);
    t = (t + Math.imul(t ^ (t >>> 7), 61 | t)) ^ t;
    return ((t ^ (t >>> 14)) >>> 0) / 4294967296;
  };
}

// --- v0.4.0 additions --------------------------------------------------------

// a beaver lodge: a dome of gnawed sticks out in the shallows (#9).
// v0.9.0: retaken at 24x14 — taller dome, pale gnawed stick-ends ('B') for
// contrast, a mud cap ('X'), two logs poking out of the pile, and a baked
// ripple row ('~') either side of the waterline.
MAPS.hut = [
  '.........XXXXX..........',
  '.......XXXXXXXXX........',
  '......uOnXXXXXXuOu......',
  '.....OunuOBuOuunuOB.....',
  '....uBuOunuOuBuOunuO....',
  'BOOOunOuBuOunOuuBnuOu...',
  'BOOuOunuOBuOunuOuuBnOu..',
  '..OunuOuBuOunOuuBnuOuO..',
  '.uOunOuBuOunuOuuBnOuOOOB',
  '.OunuOuBuOunOuuBnuOuuOOB',
  'uOunuOuBuOunOuuBnuOunuOu',
  '~~DuOunuOuBuOunOuuBnuD~~',
  '~..DDDDDDDDDDDDDDDDDD..~',
  '.~~................~~~..',
];

// a red-tailed hawk soaring, seen from above (#16)
MAPS.hawk = [
  '....II........II....',
  '..IIIIII....IIIIII..',
  '.IIIIIIII..IIIIIIII.',
  'IIIIIIIIIIIIIIIIIIII',
  '..IIIIIIIIIIIIIIII..',
  '......IIIIIIII......',
  '.......IIIIII.......',
  '........AAAA........',
  '.......AAAAAA.......',
  '.......A.AA.A.......',
];

// the canoe in side profile, hauled up on the camp beach (#13)
HD_MAPS.hdCanoeSide = [
  '.z................................z.',
  '.zz..............................zz.',
  '.czzpppppppppppppppppppppppppppppzzc',
  '.ccczzzzzzzzzzzzzzzzzzzzzzzzzzzzcccc',
  '..cccckccccccccckccccccccckcccccccc.',
  '...cCCCCCCCCCCCCCCCCCCCCCCCCCCCCCc..',
  '....CCCCCCCCCCCCCCCCCCCCCCCCCCCC....',
  '......CCCCCCCCCCCCCCCCCCCCCCCC......',
  '......ppp...........................',
  '......p.............................',
];

// camp critters (#15): a chipmunk mid-dash and a red squirrel, tail up
HD_MAPS.hdChip = [
  '.........',
  '.k...kk..',
  'Ik..kIIk.',
  'II.IwwIIk',
  '.IIIwwIIE',
  '..IIIIEE.',
  '...I..I..',
];
HD_MAPS.hdSquirrel = [
  '.AAA.....',
  'AAAAA.kk.',
  'AA.AAkAAk',
  '.AA.AAAAA',
  '..AAAAAE.',
  '...AAAE..',
  '...A..A..',
];

// v0.5.0: the tent, retaken at person scale (#1) — 64x36 with a doorway a
// tripper fits through. Overrides the small v0.3.x map above.
HD_MAPS.hdTent = [
  '................................................................',
  '................................................................',
  '................................................................',
  '................................................................',
  '................................................................',
  '........................SSSSSSSSSSSSSSSS........................',
  '.....................SSSTTTTTTTTTTTTTTTTTTT.....................',
  '...................SSTTTTTTTTTTTTTTTTTTTTTTTT...................',
  '.................SSTTTTTTTTTTTTTTTTTTTTTTTTTTTT.................',
  '................STTTTTTTTTTTttttttttTTTTTTTTTTTT................',
  '..............STTTTTTTTTttttttTTTTttttttTTTTTTTTTT..............',
  '.............STTTTTTTTttttttttTkkTttttttTTTTTTTTTTT.............',
  '............STTTTTTTtttttttttTTkkTTtttttTTTTTTTTTTTT............',
  '...........STTTTTTtttttttttttTkkkkTtttttTTTTTTTTTTTTT...........',
  '..........STTTTTTtttttttttttTTkkkkTTttttTTTTTTTTTTTTTT..........',
  '.........TTTTTTTttttttttttttTkkkkkkTttttTTTTTTTTTTTTTTT.........',
  '........TTTTTTTTtttttttttttTTkkkkkkTTtttTTTTTTTTTTTTTTTT........',
  '........TTTTTtTTtttttttttttTTkkkkkkTTtttTTTTTTTTTTTTTTTT........',
  '.......TTTTTTtTTtttttttttttTkkkkkkkkTtttTTTTTTTTTTTTTTTTT.......',
  '......TTTTTTttTTttttttttttTTkkkkkkkkTTttTTTTTTTTTTTTTTTTTT......',
  '......TTTTTtttTTttttttttttTkkkkkkkkkkTttTTTTTTTTTTTTTTTTTT......',
  '.....TTTTTttttTTtttttttttTTkkkkkkkkkkTTtTTTTTTTTTTTTTTTTTTT.....',
  '.....TTTTTttttTTtttttttttTTkkkkkkkkkkTTtTTTTTTTTTTTTTTTTTTT.....',
  '....TTTTTtttttTTttttttttTTkkkkkkkkkkkkTTTTTTTTTTTTTTTTTTTTTT....',
  '....TTTTTtttttTTttttttttTTkkkkkkkkkkkkTTTTTTTTTTTTTTTTTTTTTT....',
  '....TTTTttttttTTttttttttTkkkkkkkkkkkkkkTTTTTTTTTTTTTTTTTTTTT....',
  '...TTTTTttttttTTtttttttTTkkkkkkkkkkkkkkTTTTTTTTTTTTTTTTTTTTTT...',
  '...TTTTTttttttTTtttttttTkkkkkkkkkkkkkkkkTTTTTTTTTTTTTTTTTTTTT...',
  '...TTTTtttttttTTttttttTTkkkkkkkkkkkkkkkkTTTTTTTTTTTTTTTTTTTTT...',
  '...TTTTtttttttTTttttttTTkkkkkkkkkkkkkkkkTTTTTTTTTTTTTTTTTTTTT...',
  '..TTTTTtttttttTTttttttTkkkkkkkkkkkkkkkkkkTTTTTTTTTTTTTTTTTTTTT..',
  '..TTTpTtttttttTTtttttTTkkkkkkkkkkkkkkkkkkTTTTTTTTTTTTTTTTTpTTT..',
  '..TTpTTtttttttTTtttttTkkkkkkkkkkkkkkkkkkkkTTTTTTTTTTTTTTTTTpTT..',
  '..TpTTTtttttttTTttttTTkkkkkkkkkkkkkkkkkkkkTTTTTTTTTTTTTTTTTTpT..',
  '..xTTTTtttttttTTttttTkkkkkkkkkkkkkkkkkkkkkkTTTTTTTTTTTTTTTTTTx..',
  '..TTTTTtttttttTTtttTTkkkkkkkkkkkkkkkkkkkkkkTTTTTTTTTTTTTTTTTTT..',
];

// v0.6.0: firewood is CHOPPED now (Evrtek) — a standing-dead snag, a fallen
// log with its root wad, and the axe that turns them into armloads.
HD_MAPS.hdSnag = [
  '........B.B.........',
  '........BBB.........',
  '.......BBBB.........',
  '......uBBBB..BB.....',
  '......uBBBBBBB......',
  '..BB..uBBBB.........',
  '...BBBuBBBBX........',
  '......uBBBBX........',
  '......uBBBBX...BBB..',
  '......uBBBBXBBB.....',
  '......uuBBBX........',
  '......uuBBBX........',
  '......uuBBBX........',
  '...BBBuuBBBXX.......',
  '......uuBBBXX.......',
  '......uuBBBXX.......',
  '.....uuuBBBXX.......',
  '.....uuuBBBXX.......',
  '.....uuuBBBXX.......',
  '.....uuBBBBXX.......',
  '.....uuBBBBXXX......',
  '....uuuBBBBXXX......',
  '....uuuBBBBXXX......',
  '....uuBBBBBXXX......',
  '...uuuBBBBBXXXX.....',
  '..uuuuBBBBBXXXXX....',
  '.uuuuBBBBBBXXXXXX...',
  '....................',
  '....................',
  '....................',
  '....................',
  '....................',
];
HD_MAPS.hdFallenLog = [
  '.uBu............................',
  'uuOuu...........................',
  'uOuuu.......O....O.........O....',
  'uOOuuOOOOOOOOOOOOOOOOOOOOOOOOBB.',
  'uuOuuuuuuuuuuuuuuuuuuuuuuuuuupp.',
  'uOuuuuBuuuuuuuBuuuuuuuuBuuuuupp.',
  'uuOuuuuuuuuuuuuuuuuuuuuuuuuuuBB.',
  '.uuunnnnnnnnnnnnnnnnnnnnnnnnnnn.',
  '..uu.q..q...q..q....q...q..q....',
  '................................',
  '................................',
  '................................',
];
HD_MAPS.hdAxe = [
  '..xxxx....',
  '.xXXXxw...',
  '.xXXXxw...',
  '..xxpp....',
  '....pp....',
  '....pp....',
  '....pp....',
  '....pp....',
  '....pp....',
  '....pp....',
  '....pO....',
  '....pO....',
];

// ---------------------------------------------------------------------------
// v0.9.0 pass 1 — the feel pass. Overworld trees at forest scale (#14), the
// barrel pine that towers over the camp treeline (#3), and the carry-the-wood
// frames and ring-side pile (#10). Sprites scale only by integer texel
// multiples: 'bigger' is a new map, never a scale factor.
// ---------------------------------------------------------------------------

// a white pine, 32x48 (16x24 units, three tripper heights): five layered
// tiers, lit 'i' on the left edge and 'q' undersides, a 6-texel trunk with
// the lowest 8 rows bare. Trunk base on the bottom row.
MAPS.pine = [
  '...............ii...............',
  '..............iPPq..............',
  '..............iPPq..............',
  '.............iPPPPq.............',
  '............iPPPPPPq............',
  '.............qPPPPq.............',
  '..............qPPq..............',
  '..............qPPq..............',
  '..............iPPi..............',
  '.............iPPPPq.............',
  '............iPPPPPPq............',
  '..........iPPPPPPPPPPq..........',
  '.........iPPPPPPPPPPPPq.........',
  '...........qqPPPPPPqq...........',
  '............qPPPPPPq............',
  '..............qPPq..............',
  '..............iPPq..............',
  '............iPPPPPPq............',
  '..........iPPPPPPPPPPq..........',
  '........iPPPPPPPPPPPPPPq........',
  '......iPPPPPPPPPPPPPPPPPPq......',
  '........qqPPPPPPPPPPPPqq........',
  '...........qqPPPPPPqq...........',
  '.............qPPPPq.............',
  '.............iPPPPq.............',
  '...........iPPPPPPPPq...........',
  '........iPPPPPPPPPPPPPPq........',
  '......iPPPPPPPPPPPPPPPPPPq......',
  '...iPPPPPPPPPPPPPPPPPPPPPPPPq...',
  '......qqPPPPPPPPPPPPPPPPqq......',
  '.........qqPPPPPPPPPPqq.........',
  '.............qPPPPq.............',
  '.............iPPPPq.............',
  '..........iPPPPPPPPPPq..........',
  '......iPPPPPPPPPPPPPPPPPPq......',
  '...iPPPPPPPPPPPPPPPPPPPPPPPPq...',
  'iPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPq',
  '....qqPPPPPPPPPPPPPPPPPPPPqq....',
  '........qqPPPPPPPPPPPPqq........',
  '............qPPPPPPq............',
  '.............OOuuuu.............',
  '.............OOuuuu.............',
  '.............OOuuOu.............',
  '.............OOuuuu.............',
  '.............OOuuuu.............',
  '.............OOuuuu.............',
  '.............OOuuuu.............',
  '............OOuuuuuu............',
];

// a paper birch, 24x44 (12x22 units): airy rounded crown with gaps, white
// trunk with black bars. Trunk base on the bottom row.
MAPS.birch = [
  '.........iPPPPi.........',
  '.......iPPPPPPPPi.......',
  '.....iPPPqPPPPqPPPi.....',
  '....iPPPPPPP.PPPPPPi....',
  '...iPPqPPP...PPPqPPPi...',
  '...iPPPPPP.PPPPPPPPPi...',
  '..iPPPPPPPPPPPqPPPPPPi..',
  '..iPPqPPP..PPPPPPPqPPPi.',
  '.iPPPPPP....PPPPPPPPPPi.',
  '.iPPPqPPP..PPPqPPPP.PPi.',
  '.iPPPPPPPPPPPPPPPPP..Pi.',
  '..iPPPPqPPPPPPPPPqPPPPi.',
  '..iPPPPPP..PPPPPPPPPPi..',
  '...iPPPPP..PPPqPPPPi....',
  '...iPPqPPPPPPPPPPPPi....',
  '....iPPPPPPPPPPPqPPi....',
  '.....iPPPPP.PPPPPPi.....',
  '......iPPPqPPPPPi.......',
  '.......iPPPPPPPi........',
  '........PPbbbBP.........',
  '.........PbbbBP.........',
  '..........bbbB..........',
  '..........bbbB..........',
  '..........bkkB..........',
  '..........bbbB..........',
  '..........bbbB..........',
  '..........kbbB..........',
  '..........bbbB..........',
  '..........bbbB..........',
  '..........bbkk..........',
  '..........bbbB..........',
  '..........bbbB..........',
  '..........bbbB..........',
  '..........bkkB..........',
  '..........bbbB..........',
  '..........bbbB..........',
  '..........kbbB..........',
  '..........bbbB..........',
  '..........bbbB..........',
  '..........bbkB..........',
  '..........bbbB..........',
  '..........bbbB..........',
  '.........bbbbBB.........',
  '........bbbbBBBB........',
];

// the barrel pine, 48x104 (12x26 stage units): six layered tiers, bare trunk
// for the lowest 32 rows, and ONE bare limb stub out to the right 56 texels
// up (rows 46-48) — the rope hangs from it; the stage mirrors it per site.
HD_MAPS.hdBigPine = [
  '.......................ii.......................',
  '.......................ii.......................',
  '......................iPPq......................',
  '......................iPPq......................',
  '.....................iPPPPq.....................',
  '.....................iPPPPq.....................',
  '....................iPPPPPPq....................',
  '....................iPPPPPPq....................',
  '.....................qPPPPq.....................',
  '.....................qPPPPq.....................',
  '......................qPPq......................',
  '......................qPPq......................',
  '......................iPPi......................',
  '......................iPPq......................',
  '.....................iPPPPq.....................',
  '....................iPPPPPPq....................',
  '...................iPPPPPPPPq...................',
  '..................iPPPPPPPPPPq..................',
  '.................iPPPPPPPPPPPPq.................',
  '................iPPPPPPPPPPPPPPq................',
  '..................qqPPPPPPPPqq..................',
  '...................qqPPPPPPqq...................',
  '.....................qPPPPq.....................',
  '......................qPPq......................',
  '......................iPPq......................',
  '.....................iPPPPq.....................',
  '...................iPPPPPPPPq...................',
  '..................iPPPPPPPPPPq..................',
  '................iPPPPPPPPPPPPPPq................',
  '...............iPPPPPPPPPPPPPPPPq...............',
  '.............iPPPPPPPPPPPPPPPPPPPPq.............',
  '............iPPPPPPPPPPPPPPPPPPPPPPq............',
  '..............qqPPPPPPPPPPPPPPPPqq..............',
  '.................qqPPPPPPPPPPqq.................',
  '...................qqPPPPPPqq...................',
  '.....................qPPPPq.....................',
  '......................iPPq......................',
  '....................iPPPPPPq....................',
  '..................iPPPPPPPPPPq..................',
  '................iPPPPPPPPPPPPPPq................',
  '..............iPPPPPPPPPPPPPPPPPPq..............',
  '............iPPPPPPPPPPPPPPPPPPPPPPq............',
  '..........iPPPPPPPPPPPPPPPPPPPPPPPPPPq..........',
  '........iPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPq........',
  '...........qqPPPPPPPPPPPPPPPPPPPPPPqq...........',
  '..............qqPPPPPPPPPPPPPPPPqq..............',
  '..................qqPPPPPPPPqqOOOOOOOOOOOO......',
  '.....................qPPPPquuuuuuuuuuuuuuu......',
  '.....................iPPPPq.uuuuuuuuuuuuu.......',
  '...................iPPPPPPPPq...................',
  '................iPPPPPPPPPPPPPPq................',
  '..............iPPPPPPPPPPPPPPPPPPq..............',
  '...........iPPPPPPPPPPPPPPPPPPPPPPPPq...........',
  '.........iPPPPPPPPPPPPPPPPPPPPPPPPPPPPq.........',
  '......iPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPq......',
  '....iPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPq....',
  '........qqPPPPPPPPPPPPPPPPPPPPPPPPPPPPqq........',
  '............qqPPPPPPPPPPPPPPPPPPPPqq............',
  '................qqPPPPPPPPPPPPqq................',
  '....................qPPPPPPq....................',
  '.....................iPPPPq.....................',
  '..................iPPPPPPPPPPq..................',
  '...............iPPPPPPPPPPPPPPPPq...............',
  '............iPPPPPPPPPPPPPPPPPPPPPPq............',
  '.........iPPPPPPPPPPPPPPPPPPPPPPPPPPPPq.........',
  '......iPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPq......',
  '...iPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPq...',
  'iPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPq',
  '.....qqPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPqq.....',
  '..........qqPPPPPPPPPPPPPPPPPPPPPPPPqq..........',
  '..............qqPPPPPPPPPPPPPPPPqq..............',
  '...................qqPPPPPPqq...................',
  '....................OOuuuuuu....................',
  '....................OOuuuuuu....................',
  '....................OOuuuuuu....................',
  '....................OOuuuOuu....................',
  '....................OOuuuuuu....................',
  '....................OOuuuuuu....................',
  '....................OOuuuuuu....................',
  '....................OOuuuuuu....................',
  '....................OOuOuuuu....................',
  '....................OOuuuuuu....................',
  '....................OOuuuuuu....................',
  '....................OOuuuuuu....................',
  '....................OOuuuuuu....................',
  '....................OOuuuuuu....................',
  '....................OOuuuuOu....................',
  '....................OOuuuuuu....................',
  '....................OOuuuuuu....................',
  '....................OOuuuuuu....................',
  '....................OOuuuuuu....................',
  '....................OOuuuuuu....................',
  '....................OOuOuuuu....................',
  '....................OOuuuuuu....................',
  '....................OOuuuuuu....................',
  '....................OOuuuuuu....................',
  '....................OOuuuuuu....................',
  '....................OOuuuuuu....................',
  '....................OOuuuuuu....................',
  '....................OOuuuuuu....................',
  '....................OOuuuuuu....................',
  '...................OOOuuuuuuu...................',
  '..................OOOOuuuuuuuu..................',
  '.................OOOOuuuuuuuuuu.................',
];

// carrying the wood (#10), 24x32: a stack of three split logs across the
// chest ('O' top-lit, 'n' shadowed underside, pale 'p' cut ends two texels
// wide), the right arm strapped over the top log, the left hand under the
// stack. The stack body (rows 10-15) is symmetric about the centre so it
// reads the same mirrored; only the strap arm swaps sides. hdCarryStand takes
// hdStand's legs; the two walk frames take the legs of hdWalk1/hdWalk2.
HD_MAPS.hdCarryStand = [
  '.........hhhhhh.........',
  '........hhhhhhhh........',
  '.......hhhhhhhhhh.......',
  '.......hhhhhhhhhh.......',
  '........ssssssss........',
  '........sskssks.........',
  '........ssssssss........',
  '.........ssssss.........',
  '....rrrrrRRrrRRrrrr.....',
  '..ppOOOOOOOOOOOssrrrrr..',
  '..ppnnnnnnnnnnnnnnnnpp..',
  '.ppOOOOOOOOOOOOOOOOOOpp.',
  '.ppnnnnnnnnnnnnnnnnnnpp.',
  '..ppOOOOOOOOOOOOOOOOpp..',
  '..ppnnnnnnnnnnnnnnnnpp..',
  '.ssuuuuuuuuuuuuuuuuuuss.',
  '...ssssssrrrrrrssssss...',
  '......nnnnnnnnnnnn......',
  '......nnnnnnnnnnnn......',
  '......nnnn....nnnn......',
  '......nnnn....nnnn......',
  '......nnnn....nnnn......',
  '......nnnn....nnnn......',
  '......nnnn....nnnn......',
  '......kkkk....kkkk......',
  '.....kkkkk....kkkkk.....',
  '........................',
  '........................',
  '........................',
  '........................',
  '........................',
  '........................',
];
HD_MAPS.hdCarryWood1 = [
  '.........hhhhhh.........',
  '........hhhhhhhh........',
  '.......hhhhhhhhhh.......',
  '.......hhhhhhhhhh.......',
  '........ssssssss........',
  '........sskssks.........',
  '........ssssssss........',
  '.........ssssss.........',
  '....rrrrrRRrrRRrrrr.....',
  '..ppOOOOOOOOOOOssrrrrr..',
  '..ppnnnnnnnnnnnnnnnnpp..',
  '.ppOOOOOOOOOOOOOOOOOOpp.',
  '.ppnnnnnnnnnnnnnnnnnnpp.',
  '..ppOOOOOOOOOOOOOOOOpp..',
  '..ppnnnnnnnnnnnnnnnnpp..',
  '.ssuuuuuuuuuuuuuuuuuuss.',
  '...ssssssrrrrrrssssss...',
  '......nnnnnnnnnnnn......',
  '......nnnnnnnnnnnn......',
  '......nnnn....nnnn......',
  '......nnnn....nnnn......',
  '......nnnn....nnnn......',
  '......nnnn......nnnn....',
  '......nnnn......nnnn....',
  '......kkkk......nnnn....',
  '.....kkkkk......nnnn....',
  '................kkkk....',
  '...............kkkkk....',
  '........................',
  '........................',
  '........................',
  '........................',
];
HD_MAPS.hdCarryWood2 = [
  '.........hhhhhh.........',
  '........hhhhhhhh........',
  '.......hhhhhhhhhh.......',
  '.......hhhhhhhhhh.......',
  '........ssssssss........',
  '........sskssks.........',
  '........ssssssss........',
  '.........ssssss.........',
  '....rrrrrRRrrRRrrrr.....',
  '..ppOOOOOOOOOOOssrrrrr..',
  '..ppnnnnnnnnnnnnnnnnpp..',
  '.ppOOOOOOOOOOOOOOOOOOpp.',
  '.ppnnnnnnnnnnnnnnnnnnpp.',
  '..ppOOOOOOOOOOOOOOOOpp..',
  '..ppnnnnnnnnnnnnnnnnpp..',
  '.ssuuuuuuuuuuuuuuuuuuss.',
  '...ssssssrrrrrrssssss...',
  '......nnnnnnnnnnnn......',
  '......nnnnnnnnnnnn......',
  '......nnnn....nnnn......',
  '......nnnn....nnnn......',
  '......nnnn....nnnn......',
  '....nnnn......nnnn......',
  '....nnnn......nnnn......',
  '....nnnn......kkkk......',
  '....nnnn.....kkkkk......',
  '....kkkk................',
  '...kkkkk................',
  '........................',
  '........................',
  '........................',
  '........................',
];

// carrying the food barrel (v0.9.2, Evrtek's note: the picked-up barrel
// "floats over the player's head" — make it a carry like the logs), 24x32:
// the blue drum hugged against the chest, its top rim on the shoulder row
// (8), both arms wrapped round it — sleeves down the outside, forearms
// crossing the front, hands clasped at the centre (rows 15-16) — so a hoop
// shows above the arms and one below. It is THE barrel: barrel-blue 'W',
// black 'k' hoops and rims, the pale 'S' lid, but shaded SYMMETRICALLY
// (dark 'T' edges, one centre '~' highlight) rather than left-lit like the
// prop, so the mirrored frame reads the same. The drum hangs to the knees
// (row 21) and hides the trouser top; the legs show from row 22 —
// hdStand's for Stand, hdWalk1/hdWalk2's stride for 1/2. Feet stay on row
// 25 like every other tripper frame (drawHD anchors by the map's centre).
HD_MAPS.hdCarryBarrelStand = [
  '.........hhhhhh.........',
  '........hhhhhhhh........',
  '.......hhhhhhhhhh.......',
  '.......hhhhhhhhhh.......',
  '........ssssssss........',
  '........sskssks.........',
  '........ssssssss........',
  '.........ssssss.........',
  '....rrrrkkkkkkkkrrrr....',
  '...rrrkkSSSSSSSSkkrrr...',
  '..rrRkkkkkkkkkkkkkkRrr..',
  '..rrRTWWWWW~~WWWWWTRrr..',
  '..rrRTWWWWW~~WWWWWTRrr..',
  '..rrRTWWWWW~~WWWWWTRrr..',
  '.rrrRTWWWWW~~WWWWWTRrrr.',
  '.rrrrrrrrrssssrrrrrrrrr.',
  '..rRRRRRRRssssRRRRRRRr..',
  '.....TWWWWW~~WWWWWT.....',
  '.....kkkkkkkkkkkkkk.....',
  '.....TWWWWW~~WWWWWT.....',
  '......kWWWWWWWWWWk......',
  '.......kkkkkkkkkk.......',
  '......nnnn....nnnn......',
  '......nnnn....nnnn......',
  '......kkkk....kkkk......',
  '.....kkkkk....kkkkk.....',
  '........................',
  '........................',
  '........................',
  '........................',
  '........................',
  '........................',
];
HD_MAPS.hdCarryBarrel1 = [
  '.........hhhhhh.........',
  '........hhhhhhhh........',
  '.......hhhhhhhhhh.......',
  '.......hhhhhhhhhh.......',
  '........ssssssss........',
  '........sskssks.........',
  '........ssssssss........',
  '.........ssssss.........',
  '....rrrrkkkkkkkkrrrr....',
  '...rrrkkSSSSSSSSkkrrr...',
  '..rrRkkkkkkkkkkkkkkRrr..',
  '..rrRTWWWWW~~WWWWWTRrr..',
  '..rrRTWWWWW~~WWWWWTRrr..',
  '..rrRTWWWWW~~WWWWWTRrr..',
  '.rrrRTWWWWW~~WWWWWTRrrr.',
  '.rrrrrrrrrssssrrrrrrrrr.',
  '..rRRRRRRRssssRRRRRRRr..',
  '.....TWWWWW~~WWWWWT.....',
  '.....kkkkkkkkkkkkkk.....',
  '.....TWWWWW~~WWWWWT.....',
  '......kWWWWWWWWWWk......',
  '.......kkkkkkkkkk.......',
  '......nnnn......nnnn....',
  '......nnnn......nnnn....',
  '......kkkk......nnnn....',
  '.....kkkkk......nnnn....',
  '................kkkk....',
  '...............kkkkk....',
  '........................',
  '........................',
  '........................',
  '........................',
];
HD_MAPS.hdCarryBarrel2 = [
  '.........hhhhhh.........',
  '........hhhhhhhh........',
  '.......hhhhhhhhhh.......',
  '.......hhhhhhhhhh.......',
  '........ssssssss........',
  '........sskssks.........',
  '........ssssssss........',
  '.........ssssss.........',
  '....rrrrkkkkkkkkrrrr....',
  '...rrrkkSSSSSSSSkkrrr...',
  '..rrRkkkkkkkkkkkkkkRrr..',
  '..rrRTWWWWW~~WWWWWTRrr..',
  '..rrRTWWWWW~~WWWWWTRrr..',
  '..rrRTWWWWW~~WWWWWTRrr..',
  '.rrrRTWWWWW~~WWWWWTRrrr.',
  '.rrrrrrrrrssssrrrrrrrrr.',
  '..rRRRRRRRssssRRRRRRRr..',
  '.....TWWWWW~~WWWWWT.....',
  '.....kkkkkkkkkkkkkk.....',
  '.....TWWWWW~~WWWWWT.....',
  '......kWWWWWWWWWWk......',
  '.......kkkkkkkkkk.......',
  '....nnnn......nnnn......',
  '....nnnn......nnnn......',
  '....nnnn......kkkk......',
  '....nnnn.....kkkkk......',
  '....kkkk................',
  '...kkkkk................',
  '........................',
  '........................',
  '........................',
  '........................',
];

// the pile at the ring (#10): split logs stacked END-ON, pale faces to the
// viewer on dark rims (the rims stay dark inside the firelight, which is
// what keeps the faces reading as discs), three sizes (1-4 / 5-9 / 10+
// logs) — 20x14 / 24x20 / 28x26. Content sits in the top rows like hdRock,
// with the pad rows sized so each keeps the base offset of the smaller map
// it replaced.
HD_MAPS.hdWoodPile1 = [
  '.......nnnnnn.......',
  '.......nppppn.......',
  '.......nppppn.......',
  '.......kkkkkk.......',
  '...nnnnnn.nnnnnn....',
  '...nppppn.nppppn....',
  '...nppppn.nppppn....',
  '...kkkkkk.kkkkkk....',
  '....................',
  '....................',
  '....................',
  '....................',
  '....................',
  '....................',
];
HD_MAPS.hdWoodPile2 = [
  '.........nnnnnn.........',
  '.........nppppn.........',
  '.........nppppn.........',
  '.........kkkkkk.........',
  '.....nnnnnn.nnnnnn......',
  '.....nppppn.nppppn......',
  '.....nppppn.nppppn......',
  '.....kkkkkk.kkkkkk......',
  '..nnnnnn.nnnnnn.nnnnnn..',
  '..nppppn.nppppn.nppppn..',
  '..nppppn.nppppn.nppppn..',
  '..kkkkkk.kkkkkk.kkkkkk..',
  '........................',
  '........................',
  '........................',
  '........................',
  '........................',
  '........................',
  '........................',
  '........................',
];
HD_MAPS.hdWoodPile3 = [
  '..........nnnnnn............',
  '..........nppppn............',
  '..........nppppn............',
  '..........kkkkkk............',
  '.......nnnnnn.nnnnnn........',
  '.......nppppn.nppppn........',
  '.......nppppn.nppppn........',
  '.......kkkkkk.kkkkkk........',
  '...nnnnnn.nnnnnn.nnnnnn.....',
  '...nppppn.nppppn.nppppn.....',
  '...nppppn.nppppn.nppppn.....',
  '...kkkkkk.kkkkkk.kkkkkk.....',
  'nnnnnn.nnnnnn.nnnnnn.nnnnnn.',
  'nppppn.nppppn.nppppn.nppppn.',
  'nppppn.nppppn.nppppn.nppppn.',
  'kkkkkk.kkkkkk.kkkkkk.kkkkkk.',
  '............................',
  '............................',
  '............................',
  '............................',
  '............................',
  '............................',
  '............................',
  '............................',
  '............................',
  '............................',
];

// ---------------------------------------------------------------------------
// v0.9.0 pass 3 — the Canoe park's world and economy, plus the props the two
// parks that follow will ask for. Overworld: the berry bush (#8, PAL.berry on
// the free INK letter 'j'), four deep-woods species (#8) and a leaping fish
// for the fx channel (#5). Camp: ten site-feature props (#4) — one per
// campsite across all three parks. Animals keep the roster's convention:
// body in the top rows, blank rows under it, so the centred draw puts the
// anchor at the feet; camp props keep hdRock's (content on top, a shadow row,
// blank rows last). Head LEFT on every land animal, like the moose.
// ---------------------------------------------------------------------------

// a blueberry bush, 12x10 (6x5 units): a low mound of pine greens with five
// berry dots, and the same mound picked bare
MAPS.bush = [
  '....iPPi....',
  '..iPPPPPPq..',
  '.iPPjPPPPjq.',
  'iPPPPPjPPPPq',
  'iPjPPPPPPjPq',
  '.qPPPjPPPPq.',
  '..qqPPPPqq..',
  '....uu.uu...',
  '............',
  '............',
];
MAPS.bushBare = [
  '....iPPi....',
  '..iPPPPPPq..',
  '.iPPPPPPPPq.',
  'iPPPPPPPPPPq',
  'iPPPPPPPPPPq',
  '.qPPPPPPPPq.',
  '..qqPPPPqq..',
  '....uu.uu...',
  '............',
  '............',
];

// Ruffed Grouse, 14x12: a plump mottled-brown hen with a crest, the tail
// fanned up behind her in buff with a dark terminal band
MAPS.grouse = [
  '..........aMMa',
  '.m.......aMaaM',
  'mkm.....aMaaaM',
  '.mmm...aMaaaaM',
  '.mmmammMaamaaM',
  '..mamamamaaaM.',
  '..mmammamamM..',
  '...ammammm....',
  '....k..k......',
  '..............',
  '..............',
  '..............',
];

// Pine Marten, 14x12: long low dark body, paler face, the buff throat bib,
// bushy tail curling up at the rump
MAPS.marten = [
  '............N.',
  '.II........NN.',
  'IkIN......NNN.',
  '.NaNNNNNNNNNN.',
  '..aNNNNNNNNNN.',
  '...NNNNNNNNNN.',
  '...NN..NN..N..',
  '...NN..NN..N..',
  '..............',
  '..............',
  '..............',
  '..............',
];

// Barred Owl, 14x12: perched on a limb and facing you — round head, pale
// facial discs round dark eyes, the barred breast, yellow bill and feet
MAPS.owl = [
  '..mmmmmmmmmm..',
  '.mmbbbmmbbbmm.',
  '.mbkkbmmbkkbm.',
  '.mbbbbyybbbbm.',
  '..mmbbmmbbmm..',
  '..mbmbmmbmbm..',
  '.bmbmbmmbmbmb.',
  '..mbmbmmbmbm..',
  '...mbmbbmbm...',
  '.uuuyyuuyyuuu.',
  '..............',
  '..............',
];

// Eastern Wolf, 18x12: standing, head left, ears up — grey saddle over a
// tawny underside and legs, the tail hanging low behind. It howls; it never
// comes closer (Evrtek's ruling).
MAPS.wolf = [
  '.x.x..............',
  '.xxx..............',
  'kxxxx.xxxxxxxxxx..',
  '.xxxxxxxxxxxxxxxxx',
  '..AxxxxxxxxxxxxxxX',
  '...EAAAAAAAAAAAAxX',
  '...EE.AA...AA.AAX.',
  '...AA.AA...AA.AAX.',
  '...AA.AA...AA.AA..',
  '..................',
  '..................',
  '..................',
];

// a fish clearing the water, 12x8: silver body arched over its own leap,
// head down at the right, forked tail at the left, spray under it. The
// swimming 'fish' above stays flat; this one is the fx-channel jump.
MAPS.fishLeap = [
  '.....SSSS...',
  '...SSSSSSSS.',
  '..SSS...SSSS',
  '.SS......SkS',
  '.S........SS',
  'SS..........',
  'S.S.........',
  '~~..~.......',
];

// --- camp site features (#4), one per site -----------------------------------

// a granite whaleback, 48x20 (12x5 stage units): lit crown on the left,
// shaded flank falling away to the right, cracks and moss flecks in the
// hollows, a shadow line of loose stone at the foot
HD_MAPS.hdLedge = [
  '..................xxxxxxxxxxxx..................',
  '..............xxxxxxxxxxxxxxxxxxxx..............',
  '...........xxxxxxxxxgxxxxxxxxxxxxxxxx...........',
  '.........xxxxxxggxxxxxxxxxxxxxXxxxxxxxx.........',
  '.......xxxxxgxxxxxxxxxxxxxxxxXXxxxxxxxxxx.......',
  '.....xxxxxXxxxxxxxxxxxxxxxxxXxxxxxxxgxxxxxx.....',
  '....xxxxxXXxxxxxxxxxxxxxxxxXxxxxxxxggxxxxxxx....',
  '...xxxxxXxxxxxxxxxxxxgxxxxXxxxxxxxxXXXXXXXXXX...',
  '..xxxxxXxxxxxxxxxxxxxxxxxXXxxxxxXXXXXXXXXXXXXX..',
  '.xxxxxXxxxxxxxgxxxxxxxxxxxxxxXXXXXXXXXXXXXXXXXX.',
  'xxxxxxxxxxxxxxxxxxxxxxxxxxXXXXXXXXXXXXXXXXXXXXXX',
  'xxxXXxxxxxxxxxxxxXxxxxxxXXXXXXXXXXXXXXXXXXXXXXXX',
  '.xXXxxxxxxxxxxxxXXxxxxXXXXXXXXXXXXXXXXXXXXXXXXX.',
  '..XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX..',
  '....XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX....',
  '......X.....XX........X.......XX........X...X...',
  '................................................',
  '................................................',
  '................................................',
  '................................................',
];

// a hand-lashed log table, 40x18: five poles laid side by side, pale cut
// ends, rope lashings at both ends, two lashed legs with their feet in shadow
HD_MAPS.hdLogTable = [
  '..BOOOppOOOOOOOOOOOOOOOOOOOOOOOOppOOOB..',
  '..BuuuppuuuuuuuuuuuuuuuuuuuuuuuuppuuuB..',
  '..BOOOppOOOOOOOOOOOOOOOOOOOOOOOOppOOOB..',
  '..BuuuppuuuuuuuuuuuuuuuuuuuuuuuuppuuuB..',
  '..BOOOppOOOOOOOOOOOOOOOOOOOOOOOOppOOOB..',
  '..BuuuppuuuuuuuuuuuuuuuuuuuuuuuuppuuuB..',
  '..BOOOppOOOOOOOOOOOOOOOOOOOOOOOOppOOOB..',
  '..BuuuppuuuuuuuuuuuuuuuuuuuuuuuuppuuuB..',
  '..BOOOppOOOOOOOOOOOOOOOOOOOOOOOOppOOOB..',
  '..BuuuppuuuuuuuuuuuuuuuuuuuuuuuuppuuuB..',
  '.....pppp......................pppp.....',
  '.....Ouuu......................Ouuu.....',
  '.....Ouuu......................Ouuu.....',
  '.....Ouuu......................Ouuu.....',
  '.....Ouuu......................Ouuu.....',
  '.....kkkk......................kkkk.....',
  '........................................',
  '........................................',
];

// a glacial erratic, 28x24: one boulder the size of a canoe, frost-split
// clean down the middle into two halves with a dark cleft between them
HD_MAPS.hdErratic = [
  '.....xxxxxxx...xxxxxxxx.....',
  '...xxxxxxxxxx..xxxxxxxxxx...',
  '..xxxxgxxxxxxkkxxxxxxxxxxx..',
  '.xxxxxxxxxxxxkkxxxxxxXxxxxx.',
  '.xxxXxxxxxxxxkkxxxxxXXxxxxx.',
  'xxxXXxxxxxxxxkkxxxxxxxxxgxxx',
  'xxXxxxxxxxxxXkkXxxxxxxXXxxxx',
  'xXxxxxxxxxxXXkkXxxxxxxXxxxXx',
  'XxxxxxxxxxxXXkkXXxxxxxxxxxXX',
  'xxxxxxxxxXXXXkkXXXXxxxxxXXXX',
  'XxxxxxxxXXXXXkkXXXXXxxXXXXXX',
  'XXxxxxxXXXXXXkkXXXXXXXXXXXXX',
  'XXXXXXXXXXXXXkkXXXXXXXXXXXXX',
  '.XXXXXXXXXXXXkkXXXXXXXXXXXX.',
  '.XXXXXXXXXXXXkkXXXXXXXXXXXX.',
  '..XXXXXXXXXXXkkXXXXXXXXXXX..',
  '...XXXXXXXXXXkkXXXXXXXXXX...',
  '.....X...XX.......X...XX....',
  '............................',
  '............................',
  '............................',
  '............................',
  '............................',
  '............................',
];

// a bear-clawed birch, 24x44 (6x11 stage units): a young paper birch with a
// two-unit trunk, black bark bars, and four parallel claw rakes in dark
// 'N' at chest height, each stepping a column per row. Base on row 35;
// the eight rows under it are pad like hdBirch, so drawHDBased stands it up.
HD_MAPS.hdClawBirch = [
  '.........iPPPPPi........',
  '.......iPPPPPPPPPi......',
  '.....iPPPqPPPPPqPPPi....',
  '....iPPqPPPPPqPPPPPPi...',
  '....iPPPPPqPPPPPPqPPi...',
  '.....iPPqPPP.PqPPPPi....',
  '.......iPPPqPPPPPi......',
  '.........PPPPPP.........',
  '........PbbbbbbP........',
  '........bbbbbbbB........',
  '........bbbbbbbB........',
  '........kkkbbbbB........',
  '........bbbbbbbB........',
  '........bbbbbbbB........',
  '........bbbbkkkB........',
  '........bbbbbbbB........',
  '........NbbNbbNB........',
  '........NbbNbbNB........',
  '........bNbbNbbN........',
  '........bNbbNbbN........',
  '........bbNbbNbB........',
  '........bbNbbNbB........',
  '........bbbNbbNB........',
  '........bbbNbbNB........',
  '........bbbbbbbB........',
  '........bbbbbbbB........',
  '........bbbbbbbB........',
  '........kkkbbbbB........',
  '........bbbbbbbB........',
  '........bbbbbbbB........',
  '........bbbbbbbB........',
  '........bbbbkkkB........',
  '........bbbbbbbB........',
  '.......bbbbbbbbBB.......',
  '......bbbbbbbbbBBB......',
  '.....bbbbbbbbbbBBBB.....',
  '........................',
  '........................',
  '........................',
  '........................',
  '........................',
  '........................',
  '........................',
  '........................',
];

// the slab table, 40x16: a flat granite slab on two dry-stacked stone
// pillars, pale shim wedges levelling it, and the two skid logs it was
// rolled up on still lying in front
HD_MAPS.hdSlabTable = [
  '....XxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxX....',
  '...xxxxxxXxxxxxxxxxxxxxxXXxxxxxxxxxxx...',
  '...xxxxxxxxxxxxxxxxxxxxxxxxxxxXxxxxxx...',
  '...XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX...',
  '....XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX....',
  '........bbbb...............bbbbb........',
  '.......xxXxxX..............xXxxx........',
  '.......XXXXXX..............XXXXXX.......',
  '.......xXxxXx..............xxXxXx.......',
  '.......XXXXXX..............XXXXXX.......',
  '......xxXxxxXx............xXxxXxxX......',
  '......XXXXXXXX............XXXXXXXX......',
  '.BOOOOOOOOOOOOOOB......BOOOOOOOOOOOOOOB.',
  '.BuuuuuuuuuuuuuuB......BuuuuuuuuuuuuuuB.',
  '...q....q....q............q....q....q...',
  '........................................',
];

// a drying rack, 36x20: three thin trunks lashed between two upright poles
// at head height, a red shirt over the top rail and a pair of socks on the
// middle one
HD_MAPS.hdDryingRack = [
  '...Ou..........................Ou...',
  '...Ou..........................Ou...',
  '..pOup........................pOup..',
  '..ppppOOOOOOOOOOOOOOOOOOOOOOOOpppp..',
  '..pOup.....rrrrrrrrrrrr.......pOup..',
  '...Ou.......rrrrrrrrrr.........Ou...',
  '...Ou.......rrRrrrrRrr.........Ou...',
  '..pOup......rrrrrrrrrr........pOup..',
  '..ppppOOOOOOOOrrrrrrOOOOOOOOOOpppp..',
  '..pOup........rrrrrr.....ww...pOup..',
  '...Ou....................ww....Ou...',
  '...Ou....................ww....Ou...',
  '..pOup...................www..pOup..',
  '..ppppOOOOOOOOOOOOOOOOOOOOOOOOpppp..',
  '..pOup........................pOup..',
  '...Ou..........................Ou...',
  '...Ou..........................Ou...',
  '...Ou..........................Ou...',
  '...kk..........................kk...',
  '....................................',
];

// the reflector rock, 28x20: a boulder with one flat face turned to the
// fire ring, its lower half blackened by every fire it has thrown back
HD_MAPS.hdReflectorRock = [
  '.........xxxxxxxxxx.........',
  '......xxxxxxxxxxxxxxxx......',
  '....xxxxgxxxxxxxxxxxxxxx....',
  '...xxxxxxxxxxxxxxxxxXxxxx...',
  '..xxxXxxxxxxxxxxxxxXXxxxxx..',
  '.xxxXxxxxxxxxxxxxxXxxgxxxxx.',
  'xxxXxxxxxxxxxxxxxxxxxxxxxXXX',
  'xxXxxxxxxxxxxxxxxxxxxxxxXXXX',
  'XXxxxxxxxxxxxxxxxxxxxxxxXXXX',
  '..XXXXXXXXXXkXXkXXXXXXXXXX..',
  '..XXXXXXXkXXkXXkXXkXXXXXXX..',
  '..XXXXXXXkXXkXXkXXkXXXXXXX..',
  '..XXXXXkXkXXkXXkXXkXkXXXXX..',
  '..XXXXXkXkXXkXXkXXkXkXXXXX..',
  '..XXXXXXXXXXXXXXXXXXXXXXXX..',
  '...XXXXXXXXXXXXXXXXXXXXXX...',
  '.....X.....XX.......X...X...',
  '............................',
  '............................',
  '............................',
];

// the rock table, 40x14: one bare shelf of granite with two short log
// benches sitting on it, the lip of the shelf shaded along the bottom
HD_MAPS.hdRockTable = [
  '......xxxxxxxxxxxxxxxxxxxxxxxxxxxx......',
  '...xxxxxxxxxXxxxxxxxxxxxxxxxxxgxxxxxx...',
  '.xxxxgxxxxxxxxxxxxxxxxxxxxxXXxxxxxxxxxx.',
  'xxxxxOOOOOOOOOOOxxxxXXXxOOOOOOOOOOOxxxxx',
  'XXxxxOuuuuuuuuuOxxxxxxxxOuuuuuuuuuOxxxXX',
  'XXXxxxuuxxxxxuuxxxxxxxxxxuuxxxxxuuxxxXXX',
  'XXXXxxkkxxxxxkkxxxxxxxxxxkkxxxxxkkxxXXXX',
  'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX',
  '.XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX.',
  '...XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX...',
  '........................................',
  '........................................',
  '........................................',
  '........................................',
];

// the rail spike, 10x10: a square-headed iron spike from the old railbed,
// rusted through in ember with orange scale, lying across a fire-ring rock
HD_MAPS.hdRailSpike = [
  '..........',
  '.ee.......',
  '.eee......',
  '..eeo.....',
  '...eeo....',
  '....eeo...',
  '..xxxxeex.',
  '.xxXxxxxee',
  '.XXXXXXXX.',
  '..........',
];

// the pine ridge, 48x24: a low bank of red gravel with three red-pine
// trunks standing out of it — plated bark in canoe reds with a lit edge and
// a shadow side, roots flaring into the gravel. The crowns are above the
// frame: the RIDGE is low, the pines are not.
HD_MAPS.hdPineRidge = [
  '......OuCu............CCuu............OCCu......',
  '......CCCu............OCCu............OuCu......',
  '......OCuu............OuCu............OCCu......',
  '......OuCu............OCCu............CCuu......',
  '......OCCu............CCCu............OuCu......',
  '......CCCu............Ouuu............OCCu......',
  '......OuCu............OCCu............OCCu......',
  '......OCuu............OCCu............CuCu......',
  '......OCCu............CuCu............OCuu......',
  '......CuCu............OCCu............OCCu......',
  '......OCCu............OCuu............OuCu......',
  '......OCCu............OuCu............CCCu......',
  '......Ouuu............CCCu............OCCu......',
  '......CCCuUUeeUUUCUeUeOCCueUeeeUeUeUUeOuuu......',
  '.....OOCCuueUUUUUUeeeOOuCuueUCUUUCUUeOOCCuu.....',
  '...UOOOuCuuueUUUUeUeOOOCuuuuUeUUeeUUOOCCCuuuU...',
  '.UUeeUUeUUeUeUeUeUeeUUUeeUUeeeUUUUUUUeeCeUUUeeU.',
  'eeUUeUeUeUeeXeUUUeUeeUUUUUeUCUUUUeUeXeeXUUCeUeee',
  'UUeeUeeUUUUUeUUeeeeUeeeXeeUeUUUeeUeeUeeUUeUUCUUe',
  'CeUeUXeUXeeUeUUeUUUUUeUUeUUUUUeeUUUUUUeeUUeUeUUC',
  'eeeUUXUCeeeUeUUeUUUeUeeXeUUUUeUUUeUeUeUUXeeUUUUU',
  'XXXXXXXUXXXXUXUXXXXXUXUXXXUXXXXXXUXXXXXXXUXXXUXX',
  '................................................',
  '................................................',
];

// ---------------------------------------------------------------------------
// v0.9.0 pass 6 — the Highway 60 park-selection screen. Four overworld-density
// (2x) props for the shelf's road strip, and nothing else draws them: the
// station wagon in SIDE profile facing RIGHT (east, the way the cards run),
// its red canoe strapped HULL-UP on the rack, a park signboard for the
// shoulder, and a dust puff for the rear wheel. Body inks PAL.car / carLt on
// the last free letters 'Y' / 'Z'; 'Q' is PAL.shallow for the glass. The car
// is unbranded: a cream two-tone wagon with wood-grain doors (PAL.boxWood),
// rack towers in PAL.rockDk, tyres black with a grey hub whose white spokes
// sit on opposite diagonals in the two frames — alternate them every ~90 ms
// and the wheels turn. The maps carry no ground row: the painter puts the
// tyres on the asphalt itself.
// ---------------------------------------------------------------------------

// the wagon, 44x18 (22x9 units). Rows 0-1 are the rack towers (bar ends seen
// end-on, x10-13 and x29-32); the roof runs x6-31; tail at the left with its
// red lamps, windshield raked over rows 3-7 into the lower hood, headlamps at
// the nose; wheels x6-12 and x30-36, centre row 14, sill row 13.
MAPS.carSide1 = [
  '..........XXXX...............XXXX...........',
  '...........XX.................XX............',
  '......ZZZZZZZZZZZZZZZZZZZZZZZZZZ............',
  '.....YQQQQQYYQQQQQQQYYQQQQQQQYYQQY..........',
  '....YYQQQQQYYQQQQQQQYYQQQQQQQQYYQQY.........',
  '....YYQQQQQYYQQQQQQQYYQQQQQQQQQYYQQY........',
  '....YYQQQQQYYQQQQQQQYYQQQQQQQQQQYYQQY.......',
  '....YYQQQQQYYQQQQQQQYYQQQQQQQQQQQYYQQYYYYY..',
  '...ZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZ.',
  '..ccYUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUYYYYyy',
  '..ccYUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUYYYYyy',
  '..YYYUYkkkkkYUUUUUUUUUUUUUUUUUYkkkkkYUYYYYYY',
  '..YYYUkkkkkkkUUUUUUUUUUUUUUUUUkkkkkkkUYYYYYY',
  '..YYYYkkwxxkkYYYYYYYYYYYYYYYYYkkwxxkkYYYYYYY',
  '...XXXkkxxxkkXXXXXXXXXXXXXXXXXkkxxxkkXXXXXX.',
  '......kkxxwkk.................kkxxwkk.......',
  '......kkkkkkk.................kkkkkkk.......',
  '.......kkkkk...................kkkkk........',
];
// frame 2: the same wagon, hub spokes on the other diagonal
MAPS.carSide2 = [
  '..........XXXX...............XXXX...........',
  '...........XX.................XX............',
  '......ZZZZZZZZZZZZZZZZZZZZZZZZZZ............',
  '.....YQQQQQYYQQQQQQQYYQQQQQQQYYQQY..........',
  '....YYQQQQQYYQQQQQQQYYQQQQQQQQYYQQY.........',
  '....YYQQQQQYYQQQQQQQYYQQQQQQQQQYYQQY........',
  '....YYQQQQQYYQQQQQQQYYQQQQQQQQQQYYQQY.......',
  '....YYQQQQQYYQQQQQQQYYQQQQQQQQQQQYYQQYYYYY..',
  '...ZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZ.',
  '..ccYUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUYYYYyy',
  '..ccYUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUYYYYyy',
  '..YYYUYkkkkkYUUUUUUUUUUUUUUUUUYkkkkkYUYYYYYY',
  '..YYYUkkkkkkkUUUUUUUUUUUUUUUUUkkkkkkkUYYYYYY',
  '..YYYYkkxxwkkYYYYYYYYYYYYYYYYYkkxxwkkYYYYYYY',
  '...XXXkkxxxkkXXXXXXXXXXXXXXXXXkkxxxkkXXXXXX.',
  '......kkwxxkk.................kkwxxkk.......',
  '......kkkkkkk.................kkkkkkk.......',
  '.......kkkkk...................kkkkk........',
];

// the red canoe HULL-UP on the rack, 40x8 (20x4 units): keel highlight on
// top, the hull darkening toward the wood gunwale (row 5), the two stems
// dipping below it at the ends, and two yellow cam straps over the hull at
// x10 and x29. Draw it at (car.x + 2, car.y - 6): the gunwale then rests one
// row above the rack towers, whose bar ends show under the open middle.
MAPS.canoeRoof = [
  '............zzzzzzzzzzzzzzzz............',
  '.......cccyccccccccccccccccccyccc.......',
  '....ccccccyccccccccccccccccccycccccc....',
  '..cccccccCyCCCCCCCCCCCCCCCCCCyCccccccc..',
  '.CCCCCCCCCyCCCCCCCCCCCCCCCCCCyCCCCCCCCC.',
  'CpppppppppyppppppppppppppppppypppppppppC',
  'CC....................................CC',
  'C......................................C',
];

// a park signboard on a post, 10x14 (5x7 units): brown face with a pale rim,
// blank on purpose — no numerals, no marks (the shelf spec's clean-data
// ruling). Post rows 8-13, no ground row.
MAPS.hwySign = [
  'wwwwwwwwww',
  'wUUUUUUUUw',
  'wUUUUUUUUw',
  'wUUUUUUUUw',
  'wUUUUUUUUw',
  'wUUUUUUUUw',
  'wUUUUUUUUw',
  'wwwwwwwwww',
  '....nn....',
  '....nn....',
  '....nn....',
  '....nn....',
  '....nn....',
  '....nn....',
];

// a dust puff for the rear wheel, 6x4 (3x2 units): grey rim, paler heart
MAPS.puff = [
  '..xx..',
  '.xBBx.',
  'xBBBBx',
  '.x..x.',
];
