// PADDLER'S PARADISE — SPRITES & PALETTE (2x set, v0.2.0)
// ---------------------------------------------------------------------------
// Every sprite is a string map drawn in code (house rule: sprite maps +
// nearest-neighbour upscale, no outside art). One character = one TEXEL, and
// as of v0.2.0 there are two texels to a world unit — Evrtek's ruling that
// the game was "maybe too blocky": same framing, double the detail. The
// renderer draws the world at 2x resolution and upscales once, so everything
// still sits on one crisp grid.
// ---------------------------------------------------------------------------

'use strict';

var PAL = {
  // world
  deep:   '#17435f', water: '#1e567a', shallow:'#2b6b8f', ripple:'#3f83a8',
  sand:   '#c9b27c', sandDk: '#a8905e',
  grass:  '#2a5c35', grassDk:'#20492a', forest: '#1b3f24',
  trail:  '#8a6b45', trailDk:'#6f5436',
  rock:   '#8d8d95', rockDk: '#6e6e78',
  // flora
  pine:   '#2c6e3f', pineDk: '#1f5330', pineLt: '#3f8a52',
  birch:  '#e8e4da', birchDk:'#b8b4aa',
  trunk:  '#5d4632', trunkLt:'#7a5c42', lily: '#3f8a4f', lilyFl: '#e8b4c8',
  // things
  canoe:  '#a33e2f', canoeDk:'#7c2c21', canoeLt:'#c05540', paddle: '#c9a86a',
  tent:   '#4a7ab5', tentDk: '#375d8c',
  fire1:  '#e8842a', fire2:  '#f2c14b', ember:  '#8c3a1d',
  signOr: '#e2731f', signYl: '#e8c832', post:   '#4d3a28',
  dock:   '#9a7b52', dockDk: '#7c6140',
  barrel: '#3f6fae', boxWood:'#8a6b45',
  // creatures
  skin:   '#d9a86c', shirt:  '#b53a3a', shirtDk:'#8c2c2c', hat:    '#3a5c3a',
  moose:  '#5c4230', mooseDk:'#43301f', antler: '#c9b27c',
  loon:   '#1a1a22', loonWh: '#e8e8f0',
  heron:  '#7a8a99', beaver: '#4d3520', turtle: '#3f5c35',
  otter:  '#6b4a2f', deer:   '#a5713f', deerLt: '#c98f57',
  eagleWh:'#f0f0ea', kingf:  '#3a7ab8', bearC:  '#33241a',
  fishSv: '#9fb4c4',
  // ui
  white:  '#f2f2e8', black:  '#10100c', gold:   '#f2c14b',
  bad:    '#d94f4f', good:   '#69c977', uiBg:   'rgba(12,20,16,0.82)',
};

var INK = {
  'w': 'white',  'k': 'black',
  'c': 'canoe',  'C': 'canoeDk', 'z': 'canoeLt', 'p': 'paddle',
  's': 'skin',   'r': 'shirt',   'R': 'shirtDk', 'h': 'hat',
  't': 'tent',   'T': 'tentDk',
  'f': 'fire1',  'F': 'fire2',   'e': 'ember',
  'P': 'pine',   'q': 'pineDk',  'i': 'pineLt',
  'b': 'birch',  'B': 'birchDk', 'u': 'trunk',   'O': 'trunkLt',
  'm': 'moose',  'M': 'mooseDk', 'a': 'antler',
  'l': 'loon',   'L': 'loonWh',
  'H': 'heron',  'v': 'beaver',  'V': 'turtle',
  'I': 'otter',  'A': 'deer',    'E': 'deerLt',
  'J': 'eagleWh','K': 'kingf',   'N': 'bearC',   'S': 'fishSv',
  'o': 'signOr', 'y': 'signYl',  'n': 'post',
  'd': 'dock',   'D': 'dockDk',
  'g': 'lily',   'G': 'lilyFl',
  'x': 'rock',   'X': 'rockDk',
  'W': 'barrel', 'U': 'boxWood',
};

var MAPS = {

  // --- the tripper, 12x16, facing up --------------------------------------
  walk1: [
    '....hhhh....',
    '...hhhhhh...',
    '...hhhhhh...',
    '....ssss....',
    '....ssss....',
    '.rrrrrrrrrr.',
    'rrrrRRRRrrrr',
    'srrrRRRRrrs.',
    '.rrrRRRRrr..',
    '..rrrrrrrr..',
    '..RRr..rRR..',
    '..kk....kk..',
    '..kk....kk..',
    '..kk........',
    '..kk........',
    '............',
  ],
  walk2: [
    '....hhhh....',
    '...hhhhhh...',
    '...hhhhhh...',
    '....ssss....',
    '....ssss....',
    '.rrrrrrrrrr.',
    'rrrrRRRRrrrr',
    '.srrRRRRrrs.',
    '..rrRRRRrr..',
    '..rrrrrrrr..',
    '..RRr..rRR..',
    '..kk....kk..',
    '..kk....kk..',
    '........kk..',
    '........kk..',
    '............',
  ],
  stand: [
    '....hhhh....',
    '...hhhhhh...',
    '...hhhhhh...',
    '....ssss....',
    '....ssss....',
    '.rrrrrrrrrr.',
    'rrrrRRRRrrrr',
    '.srrRRRRrrs.',
    '..rrRRRRrr..',
    '..rrrrrrrr..',
    '..RRr..rRR..',
    '..kk....kk..',
    '..kk....kk..',
    '..kk....kk..',
    '..kk....kk..',
    '............',
  ],

  // --- the red canoe with paddler, 16x24, bow up ---------------------------
  canoeL: [
    '......zccz......',
    '.....zcCCcz.....',
    '.....cCCCCc.....',
    '....zcCCCCcz....',
    '....cCkkkkCc....',
    '....cCkkkkCc....',
    '..ppcCCCCCCc....',
    '.pppcCssssCc....',
    'pp..cCssssCc....',
    '....cCrrrrCc....',
    '....cCrRRrCc....',
    '....cCrrrrCc....',
    '....cCCCCCCc....',
    '....cCkkkkCc....',
    '....cCkkkkCc....',
    '....zcCCCCcz....',
    '....cCCCCCCc....',
    '....cCCCCCCc....',
    '....zcCCCCcz....',
    '.....cCCCCc.....',
    '.....zcCCcz.....',
    '......zccz......',
    '................',
    '................',
  ],
  canoeR: [
    '......zccz......',
    '.....zcCCcz.....',
    '.....cCCCCc.....',
    '....zcCCCCcz....',
    '....cCkkkkCc....',
    '....cCkkkkCc....',
    '....cCCCCCCcpp..',
    '....cCssssCcppp.',
    '....cCssssCc..pp',
    '....cCrrrrCc....',
    '....cCrRRrCc....',
    '....cCrrrrCc....',
    '....cCCCCCCc....',
    '....cCkkkkCc....',
    '....cCkkkkCc....',
    '....zcCCCCcz....',
    '....cCCCCCCc....',
    '....cCCCCCCc....',
    '....zcCCCCcz....',
    '.....cCCCCc.....',
    '.....zcCCcz.....',
    '......zccz......',
    '................',
    '................',
  ],

  // --- portaging: hull overhead, legs under, 16x16 -------------------------
  carry1: [
    '......zccz......',
    '....zccCCccz....',
    '..zccCCCCCCccz..',
    '.zcCCCCCCCCCCcz.',
    '.cCCCCCCCCCCCCc.',
    '.cCCCCCCCCCCCCc.',
    '.zcCCCCCCCCCCcz.',
    '..zccCCCCCCccz..',
    '....zccCCccz....',
    '......ssss......',
    '.....rrrrrr.....',
    '.....rrrrrr.....',
    '....RRr..rRR....',
    '....kk....kk....',
    '....kk..........',
    '....kk..........',
  ],
  carry2: [
    '......zccz......',
    '....zccCCccz....',
    '..zccCCCCCCccz..',
    '.zcCCCCCCCCCCcz.',
    '.cCCCCCCCCCCCCc.',
    '.cCCCCCCCCCCCCc.',
    '.zcCCCCCCCCCCcz.',
    '..zccCCCCCCccz..',
    '....zccCCccz....',
    '......ssss......',
    '.....rrrrrr.....',
    '.....rrrrrr.....',
    '....RRr..rRR....',
    '....kk....kk....',
    '..........kk....',
    '..........kk....',
  ],

  canoeBeached: [
    '..zcccccccccz...',
    '.zcCCCCCCCCCcz..',
    'zcCCkkkkkkCCCcz.',
    'zcCCCCCCCCCCCcz.',
    '.zcCCCCCCCCCcz..',
    '..zcccccccccz...',
    '................',
    '................',
  ],

  // --- flora, 2x ------------------------------------------------------------
  pine: [
    '........i.........',
    '.......iPi........',
    '......iPPPq.......',
    '.....iPPPPPq......',
    '......iPPPq.......',
    '.....iPPPPPq......',
    '....iPPPPPPPq.....',
    '...iPPPPPPPPPq....',
    '.....iPPPPPq......',
    '....iPPPPPPPq.....',
    '...iPPPPPPPPPq....',
    '..iPPPPPPPPPPPq...',
    '....iPPPPPPPq.....',
    '...iPPPPPPPPPq....',
    '..iPPPPPPPPPPPq...',
    '.iPPPPPPPPPPPPPq..',
    'iPPPPPPPPPPPPPPPq.',
    '.qqqPPPPPPPPPqqq..',
    '........Ou........',
    '........Ou........',
    '........Ou........',
    '.......OOuu.......',
    '..................',
    '..................',
  ],
  birch: [
    '.....iPPPi....',
    '...iPPPPPPPi..',
    '..iPPqPPqPPPi.',
    '.iPPPPPPPPPPi.',
    '.iPqPPPPPqPPi.',
    '..iPPPPPPPPi..',
    '...iPPPPPPi...',
    '.....PPPP.....',
    '......bb......',
    '......bB......',
    '......bb......',
    '......Bb......',
    '......bb......',
    '......bB......',
    '......bb......',
    '......bb......',
    '.....bbBb.....',
    '..............',
    '..............',
    '..............',
    '..............',
    '..............',
    '..............',
    '..............',
  ],
  rock: [
    '.....xxxx.....',
    '...xxxxxxxx...',
    '..xxXxxxxXxx..',
    '.xxxxxXXxxxxx.',
    'xxXXxxxxxxXXxx',
    '.XXXXXXXXXXXX.',
    '..............',
    '..............',
  ],
  lily: [
    '..gggg..ggG.',
    '.gggggg.ggg.',
    'ggggkggggg..',
    '.gggggg.....',
    '..gggg......',
    '............',
  ],

  // --- camp, 2x -------------------------------------------------------------
  tent: [
    '...........tt...........',
    '..........tttt..........',
    '.........tttttt.........',
    '........tttttttt........',
    '.......tttTTTTttt.......',
    '......tttTTTTTTttt......',
    '.....tttTTTTTTTTttt.....',
    '....tttTTTkkkkTTTttt....',
    '...tttTTTTkkkkTTTTttt...',
    '..tttTTTTTkkkkTTTTTttt..',
    '.tttTTTTTTkkkkTTTTTTttt.',
    'tttTTTTTTTkkkkTTTTTTTttt',
    'uu..................uu..',
    '........................',
    '........................',
    '........................',
    '........................',
    '........................',
    '........................',
    '........................',
  ],
  fire1: [
    '.....F......',
    '....fFf.....',
    '....fFFf....',
    '...ffFFf....',
    '...fFFFFf...',
    '..ffFFFFff..',
    '..fffFFfff..',
    '.effffffffe.',
    '.xeeeeeeeex.',
    'xx.x.xx.x.xx',
    '............',
    '............',
  ],
  fire2: [
    '......f.....',
    '.....Ff.....',
    '....fFFf....',
    '....FFff....',
    '...fFFFFf...',
    '..fFFffFFf..',
    '..ffFFFFff..',
    '.effffffffe.',
    '.xeeeeeeeex.',
    'xx.x.xx.x.xx',
    '............',
    '............',
  ],
  firering: [
    '..xx.xx.xx..',
    '.x..x..x..x.',
    '.x.eeeeee.x.',
    'xx.eekkee.xx',
    '.x.eeeeee.x.',
    '.x..x..x..x.',
    '..xx.xx.xx..',
    '............',
  ],
  bench: [
    'OOOOOOOOOOOOOOOO',
    'OuuuuuuuuuuuuuOO',
    '.uu..........uu.',
    '.uu..........uu.',
    '................',
    '................',
  ],
  barrel: [
    '..WWWW..',
    '.WWWWWW.',
    '.WkWWkW.',
    '.WWWWWW.',
    '.WWWWWW.',
    '.WkWWkW.',
    '.WWWWWW.',
    '..WWWW..',
    '........',
    '........',
    '........',
    '........',
  ],
  barrelHung: [
    '.....uu.....',
    '.....kk.....',
    '.....kk.....',
    '....WWWW....',
    '...WWWWWW...',
    '...WkWWkW...',
    '...WWWWWW...',
    '...WkWWkW...',
    '...WWWWWW...',
    '....WWWW....',
    '............',
    '............',
    '............',
    '............',
    '............',
    '............',
    '............',
    '............',
    '............',
    '............',
  ],
  thunderbox: [
    '..UUUUUUUU..',
    '.UUUUUUUUUU.',
    '.UUnnnnnnUU.',
    '.UUnkkkknUU.',
    '.UUnnnnnnUU.',
    '.UUUUUUUUUU.',
    '.UU......UU.',
    '............',
    '............',
    '............',
    '............',
    '............',
  ],
  deadfall: [
    '..OuuO......',
    '.OuuuuOuu...',
    'uuOuuuuuuOu.',
    '..uuOOuuuu..',
    '............',
    '............',
    '............',
    '............',
  ],

  // --- signs & furniture, 2x ------------------------------------------------
  campSign: [
    'oooooooo',
    'oo.kk.oo',
    'o.kkkk.o',
    'oo.kk.oo',
    'oooooooo',
    '...nn...',
    '...nn...',
    '...nn...',
    '...nn...',
    '...nn...',
    '...nn...',
    '........',
    '........',
    '........',
    '........',
    '........',
  ],
  portSign: [
    'yyyyyyyy',
    'yy.kk.yy',
    'y..kk..y',
    'y.kkkk.y',
    'yyyyyyyy',
    '...nn...',
    '...nn...',
    '...nn...',
    '...nn...',
    '...nn...',
    '...nn...',
    '........',
    '........',
    '........',
    '........',
    '........',
  ],
  board: [
    'nnnnnnnnnnnnnnnnnnnn',
    'nwwwwwwwwwwwwwwwwwwn',
    'nwkkwkwwkkkwwkwkkwwn',
    'nwwwwwwwwwwwwwwwwwwn',
    'nwkwkkwwkwkkkwwkkwwn',
    'nwwwwwwwwwwwwwwwwwwn',
    'nwkkkwkwwkkwwkwkwwwn',
    'nwwwwwwwwwwwwwwwwwwn',
    'nnnnnnnnnnnnnnnnnnnn',
    '.......nn...........',
    '.......nn...........',
    '.......nn...........',
    '.......nn...........',
    '....................',
    '....................',
    '....................',
    '....................',
    '....................',
  ],

  // --- wildlife, 2x ---------------------------------------------------------
  moose: [
    'aa...aa........aa...aa......',
    '.aa.aa..........aa.aa.......',
    '..aaa...............aaa.....',
    '...mm............mm.........',
    '...mmm..........mmm.........',
    '....mmmmmmmmmmmmmm..........',
    '...mmmmmmmmmmmmmmmm.........',
    '..Mmmmmmmmmmmmmmmmmm........',
    '.kMMmmmmmmmmmmmmmmmm........',
    '..MM.mmmmmmmmmmmmmm.........',
    '.....Mm..Mm..mM..mM.........',
    '.....Mm..Mm..mM..mM.........',
    '.....MM..MM..MM..MM.........',
    '............................',
    '............................',
    '............................',
    '............................',
    '............................',
    '............................',
    '............................',
    '............................',
    '............................',
  ],
  loon: [
    '..kk............',
    '.kkkk...........',
    'kkkkk...........',
    '.kkLLkkkkkkk....',
    '.kklLkLkLkLkk...',
    '..kkllkLkLklk...',
    '...kllllllllk...',
    '....llllllll....',
    '................',
    '................',
  ],
  heron: [
    '..kkk.......',
    '..HHHk......',
    '...HH.......',
    '...HH.......',
    '...HHH......',
    '....HHH.....',
    '...HHHHHH...',
    '..HHHHHHHH..',
    '..HHHHHHHH..',
    '...HHHHHH...',
    '....HHHH....',
    '.....HH.....',
    '.....kk.....',
    '.....kk.....',
    '....kk.k....',
    '............',
    '............',
    '............',
    '............',
    '............',
  ],
  beaver: [
    '...vvvvvv.....',
    '..vvvvvvvv....',
    '.kvvvvvvvvv...',
    '.vvvvvvvvvv...',
    '..vvvvvvvv....',
    '....kkkkkkkk..',
    '....kkkkkkkk..',
    '..............',
    '..............',
    '..............',
  ],
  turtle: [
    '...VVVVVV...',
    '..VVkVVkVV..',
    '.VVVVVVVVVV.',
    'kVVVVVVVVVVk',
    '.V.V....V.V.',
    '............',
    '............',
    '............',
  ],
  otter: [
    '.II.............',
    'IkII............',
    '.IIII...........',
    '..IIIIIIIII.....',
    '...IIIIIIIIIII..',
    '.....IIII...III.',
    '................',
    '................',
  ],
  deer: [
    '.a..a...............',
    '.aa.aa..............',
    '..AAA...............',
    '..AAk...............',
    '..AA................',
    '..AAEEEEEEEEE.......',
    '..AEEEEEEEEEEE......',
    '...EEEEEEEEEEE......',
    '...EE.EE..EE.EE.....',
    '...EE.EE..EE.EE.....',
    '...AA.AA..AA.AA.....',
    '....................',
    '....................',
    '....................',
    '....................',
    '....................',
    '....................',
    '....................',
    '....................',
    '....................',
  ],
  eagle: [
    'kk..................',
    '.kkk................',
    '..kkkkk....JJ.......',
    '...kkkkkkkJJk.......',
    '....kkkkkkkkkk......',
    '...kkkkkkkkk........',
    '..kkkkk.............',
    '.kkk................',
    'kk..................',
    '....................',
  ],
  kingfisher: [
    '..KKk.....',
    '.KKKKk....',
    'kKLKKK....',
    '.KKKKKKK..',
    '..KKKKK...',
    '...KK.....',
    '..........',
    '..........',
    '..........',
    '..........',
  ],
  bear: [
    '..NN..............NN..',
    '.NNNN............NNNN.',
    '.NNNNNNNNNNNNNNNNNNNN.',
    'NNNNNNNNNNNNNNNNNNNNNN',
    'NkNNNNNNNNNNNNNNNNNNNN',
    'NNNNNNNNNNNNNNNNNNNNN.',
    '.NNN.NNN......NNN.NNN.',
    '.NNN.NNN......NNN.NNN.',
    '......................',
    '......................',
    '......................',
    '......................',
    '......................',
    '......................',
    '......................',
    '......................',
  ],
  splash: [
    '....S.......',
    '.S..S...S...',
    '..S.SS.S....',
    '...SSSS.....',
    '..SSSSSS....',
    '.SSSSSSSS...',
    '............',
    '............',
  ],
  fish: [
    '....SSSS....',
    '..SSSSSSSk..',
    '.SSSSSSSSSS.',
    '..SSSSSSS...',
    '....SSSS....',
    '......S.....',
    '............',
    '............',
  ],
};

// --- builder ----------------------------------------------------------------

var SPRITES = {};

function buildSprite(name, rows, ink) {
  var h = rows.length, w = 0, y, x;
  for (y = 0; y < h; y++) w = Math.max(w, rows[y].length);
  var c = document.createElement('canvas');
  c.width = w; c.height = h;
  var g = c.getContext('2d');
  for (y = 0; y < h; y++) {
    for (x = 0; x < rows[y].length; x++) {
      var ch = rows[y][x];
      if (ch === '.' || ch === ' ') continue;
      var key = ink[ch];
      if (!key) continue;
      g.fillStyle = PAL[key];
      g.fillRect(x, y, 1, 1);
    }
  }
  SPRITES[name] = c;
  return c;
}

function buildAllSprites() {
  var name;
  for (name in MAPS) buildSprite(name, MAPS[name], INK);
  // the objective chevron, in gold
  buildSprite('marker', [
    'gg........gg',
    'ggg......ggg',
    '.ggg....ggg.',
    '..ggg..ggg..',
    '...gggggg...',
    '....gggg....',
    '.....gg.....',
    '............',
  ], { g: 'gold' });
}

// ---------------------------------------------------------------------------
// THE CAMP SET — high-fidelity sprites for the campsite scene (v0.3.0).
// The camp is a SCENE SWITCH, not a zoom (Evrtek's ruling): its own stage at
// four texels per world unit, double the overworld's density. These maps are
// drawn at that density — twice the linear detail of the overworld set — and
// only ever appear inside the camp scene.
// ---------------------------------------------------------------------------

var HD_MAPS = {

  hdStand: [
    '.........hhhhhh.........',
    '........hhhhhhhh........',
    '.......hhhhhhhhhh.......',
    '.......hhhhhhhhhh.......',
    '........ssssssss........',
    '........sskssks.........',
    '........ssssssss........',
    '.........ssssss.........',
    '....rrrrrRRrrRRrrrr.....',
    '...rrrrrrRRrrRRrrrrr....',
    '..rrrRRrrrrrrrrrrRRrr...',
    '..srrRRrrrrRRrrrrRRrrs..',
    '..ssrrrrrrRRRRrrrrrrss..',
    '..ssrrRRrrRRRRrrRRrrss..',
    '...srrRRrrrrrrrrRRrrs...',
    '....rrrrrrRRRRrrrrrr....',
    '.....rrrrrrrrrrrrrr.....',
    '......nnnnnnnnnnnn......',
    '......nnnnnnnnnnnn......',
    '......nnnn....nnnn......',
    '......nnnn....nnnn......',
    '......nnnn....nnnn......',
    '......nnnn....nnnn......',
    '......nnnn....nnnn......',
    '......kkkk....kkkk......',
    '.....kkkkk....kkkkk.....',
    '........................',
    '........................',
    '........................',
    '........................',
    '........................',
    '........................',
  ],
  hdWalk1: [
    '.........hhhhhh.........',
    '........hhhhhhhh........',
    '.......hhhhhhhhhh.......',
    '.......hhhhhhhhhh.......',
    '........ssssssss........',
    '........sskssks.........',
    '........ssssssss........',
    '.........ssssss.........',
    '....rrrrrRRrrRRrrrr.....',
    '...rrrrrrRRrrRRrrrrr....',
    '..rrrRRrrrrrrrrrrRRrr...',
    '..srrRRrrrrRRrrrrRRrrs..',
    '..ssrrrrrrRRRRrrrrrrss..',
    '..ssrrRRrrRRRRrrRRrrss..',
    '...srrRRrrrrrrrrRRrrs...',
    '....rrrrrrRRRRrrrrrr....',
    '.....rrrrrrrrrrrrrr.....',
    '......nnnnnnnnnnnn......',
    '......nnnnnnnnnnnn......',
    '......nnnn....nnnn......',
    '......nnnn....nnnn......',
    '......nnnn....nnnn......',
    '......nnnn......nnnn....',
    '......nnnn......nnnn....',
    '......kkkk......kkkk....',
    '.....kkkkk......kkkkk...',
    '........................',
    '........................',
    '........................',
    '........................',
    '........................',
    '........................',
  ],
  hdWalk2: [
    '.........hhhhhh.........',
    '........hhhhhhhh........',
    '.......hhhhhhhhhh.......',
    '.......hhhhhhhhhh.......',
    '........ssssssss........',
    '........sskssks.........',
    '........ssssssss........',
    '.........ssssss.........',
    '....rrrrrRRrrRRrrrr.....',
    '...rrrrrrRRrrRRrrrrr....',
    '..rrrRRrrrrrrrrrrRRrr...',
    '..srrRRrrrrRRrrrrRRrrs..',
    '..ssrrrrrrRRRRrrrrrrss..',
    '..ssrrRRrrRRRRrrRRrrss..',
    '...srrRRrrrrrrrrRRrrs...',
    '....rrrrrrRRRRrrrrrr....',
    '.....rrrrrrrrrrrrrr.....',
    '......nnnnnnnnnnnn......',
    '......nnnnnnnnnnnn......',
    '......nnnn....nnnn......',
    '......nnnn....nnnn......',
    '......nnnn....nnnn......',
    '....nnnn......nnnn......',
    '....nnnn......nnnn......',
    '....kkkk......kkkk......',
    '...kkkkk......kkkkk.....',
    '........................',
    '........................',
    '........................',
    '........................',
    '........................',
    '........................',
  ],

  hdTent: [
    '......................tttt......................',
    '....................tttttttt....................',
    '..................tttttttttttt..................',
    '................tttttttttttttttt................',
    '..............tttttttttttttttttttt..............',
    '............ttttttTTTTTTTTTTtttttttt............',
    '..........ttttttTTTTTTTTTTTTTTtttttttt..........',
    '........ttttttTTTTTTTTTTTTTTTTTTtttttttt........',
    '......ttttttTTTTTTTkkkkkkkkTTTTTTTtttttttt......',
    '.....tttttTTTTTTTkkkkkkkkkkkkTTTTTTTttttttt.....',
    '....tttttTTTTTTTkkkkkkkkkkkkkkTTTTTTTtttttt.....',
    '...tttttTTTTTTTkkkkkkkkkkkkkkkkTTTTTTTttttt.....',
    '..tttttTTTTTTTkkkkkkkkkkkkkkkkkkTTTTTTTtttt.....',
    '.tttttTTTTTTTkkkkkkkkkkkkkkkkkkkkTTTTTTTttt.....',
    'ttttttTTTTTTkkkkkkkkkkkkkkkkkkkkkkTTTTTTtttt....',
    'uuu...................................uuu.......',
    'uuu...................................uuu.......',
    '.................................................',
    '.................................................',
    '.................................................',
  ],

  hdFire1: [
    '..........FF............',
    '.........FFf............',
    '........fFFf.............',
    '........fFFFf............',
    '.......fFFFFFf...........',
    '......ffFFFFff...........',
    '......fFFffFFFf..........',
    '.....ffFFFFFFff..........',
    '....fffFFFFFFfff.........',
    '....ffffFFFFffff.........',
    '...efffffffffffe.........',
    '...eefffffffffee.........',
    '..xeeeeeeeeeeeeex........',
    '.xx.xx.xxxx.xx.xx........',
    '.........................',
    '.........................',
  ],
  hdFire2: [
    '............ff...........',
    '...........fFf...........',
    '..........fFFf...........',
    '.........fFFFFf..........',
    '........fFFffFf..........',
    '.......ffFFFFFFf.........',
    '......fFFFffFFFf.........',
    '.....ffFFFFFFFff.........',
    '....fffFFFFFFfff.........',
    '....ffffFFFFffff.........',
    '...efffffffffffe.........',
    '...eefffffffffee.........',
    '..xeeeeeeeeeeeeex........',
    '.xx.xx.xxxx.xx.xx........',
    '.........................',
    '.........................',
  ],
  hdRing: [
    '....xx..xxx..xx....',
    '..xx..xx...xx..xx..',
    '.x....eeeeee....x..',
    '.x..eeeekkeeee..x..',
    'xx..eekkkkkkee..xx.',
    '.x..eeeekkeeee..x..',
    '.x....eeeeee....x..',
    '..xx..xx...xx..xx..',
    '....xx..xxx..xx....',
    '...................',
  ],

  hdBench: [
    'OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO',
    'OOuuuuuuuuuuuuuuuuuuuuuuuuuuuOOO',
    'OuuOuuuuOuuuuuuuOuuuuuuOuuuuuOO.',
    '..uuuu....................uuuu..',
    '..uuuu....................uuuu..',
    '..kkkk....................kkkk..',
    '................................',
    '................................',
  ],

  hdBarrel: [
    '....WWWWWWWW....',
    '..WWWWWWWWWWWW..',
    '.WWWWWWWWWWWWWW.',
    '.WWkkWWWWWWkkWW.',
    '.WWWWWWWWWWWWWW.',
    '.WWWWWWWWWWWWWW.',
    '.WWWWWWWWWWWWWW.',
    '.WWkkWWWWWWkkWW.',
    '.WWWWWWWWWWWWWW.',
    '.WWWWWWWWWWWWWW.',
    '..WWWWWWWWWWWW..',
    '....WWWWWWWW....',
    '................',
    '................',
    '................',
    '................',
    '................',
    '................',
    '................',
    '................',
    '................',
    '................',
    '................',
    '................',
  ],
  hdBarrelHung: [
    '.........uuuu...........',
    '.........pkkp...........',
    '..........kk............',
    '..........kk............',
    '..........kk............',
    '.......WWWWWWWW.........',
    '.....WWWWWWWWWWWW.......',
    '....WWWWWWWWWWWWWW......',
    '....WWkkWWWWWWkkWW......',
    '....WWWWWWWWWWWWWW......',
    '....WWWWWWWWWWWWWW......',
    '....WWkkWWWWWWkkWW......',
    '....WWWWWWWWWWWWWW......',
    '.....WWWWWWWWWWWW.......',
    '.......WWWWWWWW.........',
    '........................',
    '........................',
    '........................',
    '........................',
    '........................',
    '........................',
    '........................',
    '........................',
    '........................',
    '........................',
    '........................',
    '........................',
    '........................',
    '........................',
    '........................',
    '........................',
    '........................',
    '........................',
    '........................',
    '........................',
    '........................',
    '........................',
    '........................',
    '........................',
    '........................',
  ],

  hdBox: [
    '....UUUUUUUUUUUUUUUU....',
    '..UUUUUUUUUUUUUUUUUUUU..',
    '.UUUnnnnnnnnnnnnnnnUUUU.',
    '.UUUnnkkkkkkkkkkknnUUUU.',
    '.UUUnnkkkkkkkkkkknnUUUU.',
    '.UUUnnnnnnnnnnnnnnnUUUU.',
    '.UUUUUUUUUUUUUUUUUUUUUU.',
    '.UUUUUUUUUUUUUUUUUUUUUU.',
    '.UUUU..............UUUU.',
    '.UUUU..............UUUU.',
    '........................',
    '........................',
    '........................',
    '........................',
    '........................',
    '........................',
  ],

  // a fallen limb with bark ridges and stubs, and two cut rounds showing
  // their end grain — wood that reads as WOOD (Evrtek's note)
  hdDeadfall: [
    '..............O.............',
    '......O.......Ou............',
    '.uuuuuOu.uuuuuOuuuuuuuu.....',
    'uOOuOuOOuOOuOuOOuOuOOuOu....',
    'uuOuuOuuOuuOuuOuuOuuOuuu....',
    '.uOOuOuOOuOOuOuOOuOuOOu.....',
    '..uu......uu.......uu.......',
    '............................',
    '....ppOO....ppOO............',
    '...pOOOOp..pOOOOp...........',
    '...pOppOp..pOppOp...........',
    '...pOOOOp..pOOOOp...........',
    '....ppOO....ppOO............',
    '............................',
    '............................',
    '............................',
  ],
  hdTentBundle: [
    '....................',
    '..ppppppppppppppp...',
    '.ptttttttttttttttp..',
    '.pttTTttttTTtttttp..',
    '.ptttttttttttttttp..',
    '..ppppppppppppppp...',
    '.....kk.....kk......',
    '....................',
  ],

  hdCanoe: [
    '....zzcccccccccccccccczz........',
    '..zzccCCCCCCCCCCCCCCCCcczz......',
    '.zccCCCCkkkkkkkkkkkkCCCCccz.....',
    'zccCCCCCkkkkkkkkkkkkCCCCCccz....',
    'zccCCCCCCCCCCCCCCCCCCCCCCccz....',
    '.zccCCCCCCCCCCCCCCCCCCCCccz.....',
    '..zzccCCCCCCCCCCCCCCCCcczz......',
    '....zzcccccccccccccccczz........',
    '................................',
    '................................',
    '................................',
    '................................',
    '................................',
    '................................',
    '................................',
    '................................',
  ],

  hdPine: [
    '................ii................',
    '...............iPPi...............',
    '..............iPPPPq..............',
    '.............iPPPPPPq.............',
    '............iPPPPPPPPq............',
    '..............iPPPPq..............',
    '.............iPPPPPPq.............',
    '...........iPPPPPPPPPPq...........',
    '..........iPPPPPPPPPPPPq..........',
    '............iPPPPPPPPq............',
    '..........iPPPPPPPPPPPPq..........',
    '........iPPPPPPPPPPPPPPPPq........',
    '..........iPPPPPPPPPPPPq..........',
    '........iPPPPPPPPPPPPPPPPq........',
    '......iPPPPPPPPPPPPPPPPPPPPq......',
    '....iPPPPPPPPPPPPPPPPPPPPPPPPq....',
    '..iPPPPPPPPPPPPPPPPPPPPPPPPPPPPq..',
    '...qqqqPPPPPPPPPPPPPPPPPPPPqqqq...',
    '...............OOuu...............',
    '...............OOuu...............',
    '...............OOuu...............',
    '...............OOuu...............',
    '..............OOOuuu..............',
    '..................................',
    '..................................',
    '..................................',
    '..................................',
    '..................................',
    '..................................',
    '..................................',
    '..................................',
    '..................................',
    '..................................',
    '..................................',
    '..................................',
    '..................................',
    '..................................',
    '..................................',
    '..................................',
    '..................................',
    '..................................',
    '..................................',
    '..................................',
    '..................................',
    '..................................',
    '..................................',
    '..................................',
    '..................................',
  ],
  hdBirch: [
    '..........iPPPPPi.........',
    '.......iPPPPPPPPPPi.......',
    '.....iPPPPqPPPPqPPPPi.....',
    '....iPPPPPPPPPPPPPPPPi....',
    '...iPPqPPPPPPPPPPPqPPPi...',
    '...iPPPPPPPPqPPPPPPPPPi...',
    '....iPPPPPPPPPPPPPPPPi....',
    '.....iPPPPPPPPPPPPPPi.....',
    '.......iPPPPPPPPPPi.......',
    '..........PPPPPP..........',
    '...........bbbb...........',
    '...........bbbB...........',
    '...........bbbb...........',
    '...........Bbbb...........',
    '...........bbbb...........',
    '...........bbbB...........',
    '...........bbbb...........',
    '...........bbbb...........',
    '...........Bbbb...........',
    '...........bbbb...........',
    '..........bbbBbb..........',
    '..........................',
    '..........................',
    '..........................',
    '..........................',
    '..........................',
    '..........................',
    '..........................',
    '..........................',
    '..........................',
    '..........................',
    '..........................',
    '..........................',
    '..........................',
    '..........................',
    '..........................',
    '..........................',
    '..........................',
    '..........................',
    '..........................',
    '..........................',
    '..........................',
  ],
  hdRock: [
    '..........xxxxxxxx..........',
    '......xxxxxxxxxxxxxx........',
    '....xxxxXXxxxxxxXXxxxx......',
    '..xxxxxxxxxxXXxxxxxxxxxx....',
    '.xxxXXxxxxxxxxxxxxxxXXxxx...',
    '.XXXXXXXXXXXXXXXXXXXXXXXX...',
    '.............................',
    '.............................',
  ],
  hdSign: [
    'oooooooooooooooo',
    'oooo..kk..oooooo',
    'ooo..kkkk..ooooo',
    'oo..kk..kk..oooo',
    'oooooooooooooooo',
    'oooooooooooooooo',
    '......nnnn......',
    '......nnnn......',
    '......nnnn......',
    '......nnnn......',
    '......nnnn......',
    '......nnnn......',
    '......nnnn......',
    '................',
    '................',
    '................',
    '................',
    '................',
    '................',
    '................',
    '................',
    '................',
    '................',
    '................',
    '................',
    '................',
    '................',
    '................',
    '................',
    '................',
    '................',
    '................',
  ],
  hdTuft: [
    '.g..g.g.',
    'g.gg.g..',
    '.g.g..g.',
    '........',
  ],
};

function buildHDSprites() {
  var name;
  for (name in HD_MAPS) buildSprite(name, HD_MAPS[name], INK);
}

// --- deterministic PRNG (mulberry32) ---------------------------------------
function rngFrom(seed) {
  var a = seed >>> 0;
  return function () {
    a |= 0; a = (a + 0x6D2B79F5) | 0;
    var t = Math.imul(a ^ (a >>> 15), 1 | a);
    t = (t + Math.imul(t ^ (t >>> 7), 61 | t)) ^ t;
    return ((t ^ (t >>> 14)) >>> 0) / 4294967296;
  };
}

// --- v0.4.0 additions --------------------------------------------------------

// a beaver lodge: a dome of gnawed sticks out in the shallows (#9)
MAPS.hut = [
  '......uOu..uu.....',
  '....uOuuOnuOu.....',
  '...OuunOuunuOu....',
  '..uOunuuOuuOnuu...',
  '.uunuOuunOuuOuOu..',
  '.OuuOnuuOuunuuOu..',
  'uunuuOuunuuOuunuu.',
  'uOuunuuOuunuuOuOu.',
  '..DD..DD..DD..D...',
];

// a red-tailed hawk soaring, seen from above (#16)
MAPS.hawk = [
  '....II........II....',
  '..IIIIII....IIIIII..',
  '.IIIIIIII..IIIIIIII.',
  'IIIIIIIIIIIIIIIIIIII',
  '..IIIIIIIIIIIIIIII..',
  '......IIIIIIII......',
  '.......IIIIII.......',
  '........AAAA........',
  '.......AAAAAA.......',
  '.......A.AA.A.......',
];

// the canoe in side profile, hauled up on the camp beach (#13)
HD_MAPS.hdCanoeSide = [
  '..z..............................z..',
  '..zz............................zz..',
  '..czz..........................zzc..',
  '..cczzzzzzzzzzzzzzzzzzzzzzzzzzzzcc..',
  '..cccckcccccccckcccccccckcccccccc...',
  '...cCCCCCCCCCCCCCCCCCCCCCCCCCCCc....',
  '....CCCCCCCCCCCCCCCCCCCCCCCCCC......',
  '.....CCCCCCCCCCCCCCCCCCCCCCC........',
  '......ppp...........................',
  '......p.............................',
];

// camp critters (#15): a chipmunk mid-dash and a red squirrel, tail up
HD_MAPS.hdChip = [
  '.........',
  '.k...kk..',
  'Ik..kIIk.',
  'II.IwwIIk',
  '.IIIwwIIE',
  '..IIIIEE.',
  '...I..I..',
];
HD_MAPS.hdSquirrel = [
  '.AAA.....',
  'AAAAA.kk.',
  'AA.AAkAAk',
  '.AA.AAAAA',
  '..AAAAAE.',
  '...AAAE..',
  '...A..A..',
];

// v0.5.0: the tent, retaken at person scale (#1) — 64x36 with a doorway a
// tripper fits through. Overrides the small v0.3.x map above.
HD_MAPS.hdTent = [
  '................................................................',
  '................................................................',
  '................................................................',
  '................................................................',
  '................................................................',
  '........................TTTTTTTTTTTTTTTT........................',
  '.....................TTTTTTTTTTTTTTTTTTTTTT.....................',
  '...................TTTTTTTTTTTTTTTTTTTTTTTTTT...................',
  '.................TTTTTTTTTTTTTTTTTTTTTTTTTTTTTT.................',
  '................TTTTTTTTTTTTttttttttTTTTTTTTTTTT................',
  '..............TTTTTTTTTTttttttTTTTttttttTTTTTTTTTT..............',
  '.............TTTTTTTTTttttttttTkkTttttttTTTTTTTTTTT.............',
  '............TTTTTTTTtttttttttTTkkTTtttttTTTTTTTTTTTT............',
  '...........TTTTTTTtttttttttttTkkkkTtttttTTTTTTTTTTTTT...........',
  '..........TTTTTTTtttttttttttTTkkkkTTttttTTTTTTTTTTTTTT..........',
  '.........TTTTTTTttttttttttttTkkkkkkTttttTTTTTTTTTTTTTTT.........',
  '........TTTTTTTTtttttttttttTTkkkkkkTTtttTTTTTTTTTTTTTTTT........',
  '........TTTTTtTTtttttttttttTTkkkkkkTTtttTTTTTTTTTTTTTTTT........',
  '.......TTTTTTtTTtttttttttttTkkkkkkkkTtttTTTTTTTTTTTTTTTTT.......',
  '......TTTTTTttTTttttttttttTTkkkkkkkkTTttTTTTTTTTTTTTTTTTTT......',
  '......TTTTTtttTTttttttttttTkkkkkkkkkkTttTTTTTTTTTTTTTTTTTT......',
  '.....TTTTTttttTTtttttttttTTkkkkkkkkkkTTtTTTTTTTTTTTTTTTTTTT.....',
  '.....TTTTTttttTTtttttttttTTkkkkkkkkkkTTtTTTTTTTTTTTTTTTTTTT.....',
  '....TTTTTtttttTTttttttttTTkkkkkkkkkkkkTTTTTTTTTTTTTTTTTTTTTT....',
  '....TTTTTtttttTTttttttttTTkkkkkkkkkkkkTTTTTTTTTTTTTTTTTTTTTT....',
  '....TTTTttttttTTttttttttTkkkkkkkkkkkkkkTTTTTTTTTTTTTTTTTTTTT....',
  '...TTTTTttttttTTtttttttTTkkkkkkkkkkkkkkTTTTTTTTTTTTTTTTTTTTTT...',
  '...TTTTTttttttTTtttttttTkkkkkkkkkkkkkkkkTTTTTTTTTTTTTTTTTTTTT...',
  '...TTTTtttttttTTttttttTTkkkkkkkkkkkkkkkkTTTTTTTTTTTTTTTTTTTTT...',
  '...TTTTtttttttTTttttttTTkkkkkkkkkkkkkkkkTTTTTTTTTTTTTTTTTTTTT...',
  '..TTTTTtttttttTTttttttTkkkkkkkkkkkkkkkkkkTTTTTTTTTTTTTTTTTTTTT..',
  '..TTTpTtttttttTTtttttTTkkkkkkkkkkkkkkkkkkTTTTTTTTTTTTTTTTTpTTT..',
  '..TTpTTtttttttTTtttttTkkkkkkkkkkkkkkkkkkkkTTTTTTTTTTTTTTTTTpTT..',
  '..TpTTTtttttttTTttttTTkkkkkkkkkkkkkkkkkkkkTTTTTTTTTTTTTTTTTTpT..',
  '..xTTTTtttttttTTttttTkkkkkkkkkkkkkkkkkkkkkkTTTTTTTTTTTTTTTTTTx..',
  '..TTTTTtttttttTTtttTTkkkkkkkkkkkkkkkkkkkkkkTTTTTTTTTTTTTTTTTTT..',
];

// v0.6.0: firewood is CHOPPED now (Evrtek) — a standing-dead snag, a fallen
// log with its root wad, and the axe that turns them into armloads.
HD_MAPS.hdSnag = [
  '......BB........',
  '.....uBB........',
  '.....uB.........',
  '..BB.uB..BB.....',
  '...BBuBBB.......',
  '.....uB.........',
  '.....uB....BB...',
  '.....uBBBBB.....',
  '.BBB.uB.........',
  '...BBuB.........',
  '.....uB.........',
  '.....uBB........',
  '.....uuB........',
  '.....uuB........',
  '....BuuBB.......',
  '.....uuB........',
  '.....uuB........',
  '.....uuBB.......',
  '....uuuBB.......',
  '....uuuBB.......',
  '...uuuuBBB......',
  '..uuuuuBBBB.....',
];
HD_MAPS.hdFallenLog = [
  '.uBu............................',
  'uuOuu...........................',
  'uOuuBOOOOOOOOOOOOOOOOOOOOOOOu...',
  'uOOuuuuuuuuuuuuuuuuuuuBuuuuuuu..',
  'uuOuuuuBuuuuuuuuuBuuuuuuuuuuuu..',
  '.uu.q..q...q..q....q...q..q.....',
];
HD_MAPS.hdAxe = [
  '..xxxx....',
  '.xXXXxw...',
  '.xXXXxw...',
  '..xxpp....',
  '....pp....',
  '....pp....',
  '....pp....',
  '....pp....',
  '....pp....',
  '....pp....',
  '....pO....',
  '....pO....',
];
